$version: "2.0"

namespace error

use smithytranslate#errorMessage

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Cloudiness percentage.\n        title: null\n        multipleOf: null\n        maximum: 100\n        exclusiveMaximum: null\n        minimum: 0\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure All {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [string]\n        format: null\n        $ref: null\n        description: Internal parameter.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Base {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Internal response status code.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Cod {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Latitude of the location.\n        title: null\n        multipleOf: null\n        maximum: 90\n        exclusiveMaximum: null\n        minimum: -90\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure CoordinatesLat {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Longitude of the location.\n        title: null\n        multipleOf: null\n        maximum: 180\n        exclusiveMaximum: null\n        minimum: -180\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure CoordinatesLon {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [string]\n        format: null\n        $ref: null\n        description: Country code.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Country {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: City identifier.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure CurrentWeatherResponseId {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Meteorological wind direction in degrees.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Deg {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [string]\n        format: null\n        $ref: null\n        description: Weather condition within the group.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Description {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Time of data calculation as a Unix timestamp in UTC.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Dt {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Temperature adjusted for human perception.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure FeelsLike {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: null\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure GetCurrentWeatherInputLat {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: null\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure GetCurrentWeatherInputLon {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Atmospheric pressure at ground level in hPa, where available.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure GrndLevel {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Wind gust speed, where available.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Gust {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Humidity percentage.\n        title: null\n        multipleOf: null\n        maximum: 100\n        exclusiveMaximum: null\n        minimum: 0\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Humidity {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [string]\n        format: null\n        $ref: null\n        description: Weather icon identifier.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Icon {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [string]\n        format: null\n        $ref: null\n        description: null\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Lang {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [string]\n        format: null\n        $ref: null\n        description: Weather condition group, such as Rain, Snow, or Clouds.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Main {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Internal parameter present in some responses.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Message {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [string]\n        format: null\n        $ref: null\n        description: null\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Mode {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Precipitation volume for the preceding hour in mm/h.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure n1h {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [string]\n        format: null\n        $ref: null\n        description: City name.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Name {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Atmospheric pressure at sea level in hPa.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Pressure {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Atmospheric pressure at sea level in hPa, where available.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure SeaLevel {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Wind speed in units selected by the request.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Speed {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Sunrise time as a Unix timestamp in UTC.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Sunrise {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Sunset time as a Unix timestamp in UTC.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Sunset {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Internal parameter.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure SystemMetadataId {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Current temperature.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Temp {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Optional maximum currently observed temperature within the location.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure TempMax {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [number]\n        format: null\n        $ref: null\n        description: Optional minimum currently observed temperature within the location.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure TempMin {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Shift in seconds from UTC.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Timezone {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Internal parameter.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Type {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [string]\n        format: null\n        $ref: null\n        description: null\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Units {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Visibility in metres, with a maximum reported value of 10 km.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Visibility {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [array]\n        format: null\n        $ref: null\n        description: null\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure Weather {}

@errorMessage("Schema not supported:\nclass JsonSchema {\n    class Schema {\n        type: [integer]\n        format: null\n        $ref: null\n        description: Weather condition identifier.\n        title: null\n        multipleOf: null\n        maximum: null\n        exclusiveMaximum: null\n        minimum: null\n        exclusiveMinimum: null\n        maxLength: null\n        minLength: null\n        pattern: null\n        maxItems: null\n        minItems: null\n        uniqueItems: null\n        maxProperties: null\n        minProperties: null\n        required: null\n        not: null\n        properties: null\n        additionalProperties: null\n        nullable: null\n        readOnly: null\n        writeOnly: null\n        example: null\n        externalDocs: null\n        deprecated: null\n        discriminator: null\n        xml: null\n        patternProperties: null\n        contains: null\n        $id: null\n        $anchor: null\n        $schema: null\n        $vocabulary: null\n        $dynamicAnchor: null\n        const: null\n        contentEncoding: null\n        contentMediaType: null\n        contentSchema: null\n        propertyNames: null\n        unevaluatedProperties: null\n        maxContains: null\n        minContains: null\n        additionalItems: null\n        unevaluatedItems: null\n        _if: null\n        _else: null\n        then: null\n        dependentRequired: null\n        dependentSchemas: null\n        $comment: null\n        prefixItems: null\n    }\n}")
structure WeatherConditionId {}
