[versions]
smithy = "1.72.0"
smithy-gradle = "1.5.0"
junit = "5.14.3"

[libraries]
smithy-build = { module = "software.amazon.smithy:smithy-build", version.ref = "smithy" }
smithy-codegen = { module = "software.amazon.smithy:smithy-codegen-core", version.ref = "smithy" }
smithy-jsonschema = { module = "software.amazon.smithy:smithy-jsonschema", version.ref = "smithy" }
smithy-model = { module = "software.amazon.smithy:smithy-model", version.ref = "smithy" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
smithy-base = { id = "software.amazon.smithy.gradle.smithy-base", version.ref = "smithy-gradle" }
