[versions]
smithy-gradle = "1.5.0"
junit = "5.14.3"
checkstyle = "14.0.0"
spotless = "8.10.1"
google-java-format = "1.36.1"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
smithy-base = { id = "software.amazon.smithy.gradle.smithy-base", version.ref = "smithy-gradle" }
smithy-jar = { id = "software.amazon.smithy.gradle.smithy-jar", version.ref = "smithy-gradle" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
