"""
Code generation: manifest validation, and what comes out the other end.

The fixture is a three-endpoint slice of a real vendor document, so these tests exercise the
awkward parts of a genuine spec — dotted filter names, an enum on one endpoint's `sort` and
none on another's, a default that already carries its sort direction.
"""

import ast
import asyncio
import copy
import importlib
import json
import string
import sys
from datetime import date
from pathlib import Path
from typing import Any

import httpx2
import pytest
from pydantic import ValidationError

from spitzeisen import AsyncSpitzeisenConfig, NoLimit
from spitzeisen.codegen.cli import is_current, normalize_model_header, write
from spitzeisen.codegen.generate import GeneratedModule, generate, generated_model_names, model_exports_module
from spitzeisen.codegen.manifest import Manifest
from spitzeisen.testing import FakeRouter

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture
def spec() -> dict[str, Any]:
    """A slice of a real vendor OpenAPI document."""
    return json.loads((FIXTURES / "vendor.json").read_text())


def manifest_dict(**overrides: Any) -> dict[str, Any]:
    """A minimal but realistic manifest."""
    base: dict[str, Any] = {
        "vendor": "example",
        "base_url": "https://api.example.test",
        "package": "example_api",
        "client_name": "ExampleApi",
        "endpoints": {
            "splits": {
                "path": "/stocks/v1/splits",
                "method_name": "get_splits",
                "model": "Split",
                "cost": 1,
                "pagination": "page_number",
                "page_size_param": "limit",
                "max_page_size": 5000,
                "sort_style": "suffix",
                "sort_param": "sort",
                "summary": "Get splits, validated into `Split` models.",
                "params": {
                    "adjustment_type.any_of": {
                        "name": "adjustment_types",
                        "coercion_style": "comma_choice_list",
                        "literal": "AdjustmentType",
                    },
                },
            },
        },
    }
    base.update(overrides)
    return base


def render(spec: dict[str, Any] | None, **overrides: Any) -> dict[str, str]:
    """Generate and return the modules keyed by a readable suffix of their path."""
    manifest = Manifest.model_validate(manifest_dict(**overrides))
    package_root = Path("example_api")
    modules = generate(manifest, _complete_openapi(spec, manifest), package_root)
    return {module.path.relative_to(package_root).as_posix(): module.source for module in modules}


def _complete_openapi(spec: dict[str, Any] | None, manifest: Manifest) -> dict[str, Any]:
    """Make small inline test cases valid OpenAPI documents before invoking the typed parser."""
    if spec is None:
        spec = {"paths": {}}
        for endpoint in manifest.endpoints.values():
            path_parameters = [
                {
                    "name": name,
                    "in": "path",
                    "required": True,
                    "schema": {"type": "string"},
                }
                for _, name, _, _ in string.Formatter().parse(endpoint.path)
                if name
            ]
            spec["paths"][endpoint.path] = {
                endpoint.method.value: {
                    "parameters": path_parameters,
                    "responses": {"200": {"description": "OK"}},
                },
            }
    if "openapi" in spec:
        return spec
    completed = copy.deepcopy(spec)
    completed.update(
        {
            "openapi": "3.1.0",
            "info": {"title": "Inline test API", "version": "1.0.0"},
            **completed,
        },
    )
    for path_item in completed.get("paths", {}).values():
        for method in ("get", "put", "post", "delete", "options", "head", "patch", "trace"):
            if method in path_item:
                path_item[method].setdefault("responses", {"200": {"description": "OK"}})
    return completed


def test_generated_model_header_is_a_prose_comment() -> None:
    """The upstream metadata header should not resemble commented-out configuration."""
    source = "# generated by datamodel-codegen:\n#   filename:  pruned.json\n\nclass Thing:\n    pass\n"

    assert normalize_model_header(source) == (
        "# Generated by datamodel-code-generator from selected OpenAPI operations.\n\nclass Thing:\n    pass\n"
    )


def test_generated_model_names_reads_top_level_public_classes() -> None:
    """The public facade contains schema classes, not imports or private implementation helpers."""
    source = "class Wind:\n    pass\n\nclass _Helper:\n    pass\n\nVALUE = 1\nclass WeatherResponse:\n    pass\n"

    assert generated_model_names(source) == ["Wind", "WeatherResponse"]


def test_model_exports_promote_response_extensions_and_nested_schema_types() -> None:
    """Consumers can name nested types while root responses resolve to user-owned subclasses."""
    manifest = Manifest.model_validate(manifest_dict())
    source = "class Wind:\n    pass\n\nclass Split:\n    pass\n"

    module = model_exports_module(manifest, Path("example_api"), source)

    assert module.path == Path("example_api/models/_exports.py")
    assert not module.create_once
    assert "from example_api.models._generated import Wind" in module.source
    assert "from example_api.models.splits import Split" in module.source
    assert "from example_api.models._generated import Split" not in module.source
    assert '"Split",' in module.source
    assert '"Wind",' in module.source
    ast.parse(module.source)


def test_endpoint_cost_must_be_scalar() -> None:
    """One endpoint draws one scalar amount from the configured limiter."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["cost"] = {"daily": 1}

    with pytest.raises(ValidationError, match="valid number"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


def test_a_choice_style_param_needs_a_literal() -> None:
    """`comma_choice_list` validates against a Literal, so it has to be told which one."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["params"]["adjustment_type.any_of"].pop("literal")

    with pytest.raises(ValidationError, match="requires `literal`"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


def test_a_required_parameter_cannot_also_have_a_default() -> None:
    """A default makes a parameter optional to the caller, so it cannot be required too."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["params"]["adjustment_type.any_of"].update({"required": True, "default": "[]"})

    with pytest.raises(ValidationError, match="cannot also declare a default"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


def test_parameter_defaults_are_literals_not_generated_source() -> None:
    """A manifest cannot smuggle executable expressions into a generated signature."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["params"]["adjustment_type.any_of"]["default"] = "load_secret()"

    with pytest.raises(ValidationError, match="must be a Python literal"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


def test_max_page_size_requires_its_wire_parameter_name() -> None:
    """OpenAPI does not identify pagination parameters, so the manifest must do so."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"].pop("page_size_param")

    with pytest.raises(ValidationError, match=r"max_page_size.*requires.*page_size_param"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


@pytest.mark.parametrize(
    ("settings", "match"),
    [
        ({"sort_style": "suffix"}, r"sort_style='suffix'.*requires `sort_param`"),
        (
            {"sort_style": "suffix", "sort_param": "ordering", "order_param": "direction"},
            r"sort_style='suffix'.*cannot declare `order_param`",
        ),
        (
            {"sort_style": "param", "sort_param": "ordering"},
            r"sort_style='param'.*requires `order_param`",
        ),
    ],
)
def test_sorting_wire_parameters_must_match_the_selected_style(settings: dict[str, str], match: str) -> None:
    """Sorting metadata is explicit and contradictory combinations fail at manifest load."""
    endpoints = {"records": {"path": "/records", "method_name": "get_records", "model": "Record", **settings}}

    with pytest.raises(ValidationError, match=match):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


def test_single_resource_policy_rejects_collection_controls() -> None:
    """A setting the single-object renderer cannot honor is rejected rather than ignored."""
    endpoints = single_endpoint(sort_style="suffix", sort_param="sort", sort_default="name", order_default="asc")

    with pytest.raises(ValidationError, match=r"single.*collection sorting"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


@pytest.mark.parametrize("coerce_function", ["not.valid", "class"])
def test_a_custom_coerce_function_must_be_a_client_params_identifier(coerce_function: str) -> None:
    """The manifest names a client-owned import, not an arbitrary source expression."""
    endpoints = manifest_dict()["endpoints"]
    parameter = endpoints["splits"]["params"]["adjustment_type.any_of"]
    parameter["coercion_style"] = "plain"
    parameter["coerce_function"] = coerce_function

    with pytest.raises(ValidationError, match="valid Python identifier"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


def test_a_custom_coerce_function_cannot_compete_with_a_builtin_style() -> None:
    """A parameter must have exactly one source of coercion behavior."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["params"]["adjustment_type.any_of"]["coerce_function"] = "coerce_adjustment_types"

    with pytest.raises(ValidationError, match="cannot be combined"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


def test_an_endpoint_missing_from_the_spec_stops_generation(spec: dict[str, Any]) -> None:
    """
    Vendor drift must fail loudly.

    This is the check that catches a path being renamed under us — the reason the manifest is
    resolved against the document rather than trusted on its own.
    """
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["path"] = "/stocks/v1/splits-renamed"

    with pytest.raises(ValueError, match="vendor may have moved or renamed it"):
        render(spec, endpoints=endpoints)


def test_manifest_selects_methods_but_the_runtime_reports_unsupported_generation(spec: dict[str, Any]) -> None:
    """The compiler preserves every method while the current GET renderer has an explicit boundary."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["method"] = "post"
    path_item = spec["paths"]["/stocks/v1/splits"]
    path_item["post"] = path_item.pop("get")

    with pytest.raises(ValueError, match="currently generates GET requests only"):
        render(spec, endpoints=endpoints)


def test_a_path_without_get_stops_generation(spec: dict[str, Any]) -> None:
    """A matching path is insufficient when it does not expose the supported GET operation."""
    path_item = spec["paths"]["/stocks/v1/splits"]
    path_item["post"] = path_item.pop("get")

    with pytest.raises(ValueError, match=r"GET /stocks/v1/splits.*absent"):
        render(spec)


def test_generated_modules_parse(spec: dict[str, Any]) -> None:
    """Whatever else is true, the output has to be Python."""
    for source in render(spec).values():
        ast.parse(source)


def test_both_surfaces_are_generated(spec: dict[str, Any]) -> None:
    """One entry yields regenerated bases plus create-once public extension modules."""
    assert set(render(spec)) == {
        "_async/_generated/__init__.py",
        "_async/_generated/splits.py",
        "_async/__init__.py",
        "_async/splits.py",
        "_async/_generated/client.py",
        "_async/client.py",
        "_sync/_generated/__init__.py",
        "_sync/_generated/splits.py",
        "_sync/__init__.py",
        "_sync/splits.py",
        "_sync/_generated/client.py",
        "_sync/client.py",
        "models/__init__.py",
        "models/splits.py",
    }


def test_public_endpoint_and_client_scaffolds_wrap_generated_bases(spec: dict[str, Any]) -> None:
    """SDK authors receive public extension points and complete aggregate client wiring."""
    modules = render(spec)

    endpoint = modules["_async/splits.py"]
    assert endpoint.startswith('"""Splits API."""')
    assert "from example_api._async._generated.splits import AsyncSplitsApiBase" in endpoint
    assert "class AsyncSplitsApi(AsyncSplitsApiBase):" in endpoint
    assert '"""Get splits, validated into `Split` models."""' in endpoint
    assert "Public extension point" not in endpoint

    endpoint_base = modules["_async/_generated/splits.py"]
    assert "AsyncSpitzeisenApi," in endpoint_base
    assert "SpitzeisenEndpointSpec," in endpoint_base
    assert "class AsyncSplitsApiBase(AsyncSpitzeisenApi):" in endpoint_base

    client_base = modules["_async/_generated/client.py"]
    assert "class AsyncExampleApiBase:" in client_base
    assert "from spitzeisen import AsyncSpitzeisenConfig" in client_base
    assert "def __init__(self, config: AsyncSpitzeisenConfig) -> None:" in client_base
    assert "self.splits_api = AsyncSplitsApi(config)" in client_base
    assert "await endpoint_api.__aenter__()" in client_base

    client = modules["_async/client.py"]
    assert client.startswith('"""Example API client."""')
    assert "from example_api._async._generated.client import AsyncExampleApiBase" in client
    assert "class AsyncExampleApi(AsyncExampleApiBase):" in client
    assert '"""Client for the Example API."""' in client
    assert "awaitable" not in client
    assert "Public extension point" not in client

    synchronous = modules["_sync/_generated/client.py"]
    assert "class SyncExampleApiBase:" in synchronous
    assert "endpoint_api.__enter__()" in synchronous
    assert "await" not in synchronous

    sync_public = modules["_sync/client.py"]
    assert '"""Client for the Example API."""' in sync_public
    assert "blocking" not in sync_public
    assert "blocking" not in modules["_sync/splits.py"]

    model = modules["models/splits.py"]
    assert "from example_api.models._generated import Split as GeneratedSplit" in model
    assert "class Split(GeneratedSplit):" in model

    model_facade = modules["models/__init__.py"]
    assert "from example_api.models._exports import *" in model_facade


def test_public_endpoint_docstring_has_a_friendly_fallback(spec: dict[str, Any]) -> None:
    """A manifest without a summary still produces useful public API documentation."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"].pop("summary")

    endpoint = render(spec, endpoints=endpoints)["_async/splits.py"]

    assert '"""Access the splits API."""' in endpoint


def test_only_public_extension_modules_are_create_once(spec: dict[str, Any]) -> None:
    """Generated bases stay replaceable while public extension files become SDK-owned."""
    package_root = Path("example_api")
    manifest = Manifest.model_validate(manifest_dict())
    modules = generate(manifest, spec, package_root)

    create_once = {module.path.relative_to(package_root).as_posix() for module in modules if module.create_once}
    assert create_once == {
        "_async/__init__.py",
        "_async/splits.py",
        "_async/client.py",
        "_sync/__init__.py",
        "_sync/splits.py",
        "_sync/client.py",
        "models/__init__.py",
        "models/splits.py",
    }


def test_writer_preserves_create_once_public_modules(tmp_path: Path) -> None:
    """Regeneration updates bases without overwriting SDK-owned public subclasses."""
    generated_path = tmp_path / "_generated" / "things.py"
    public_path = tmp_path / "things.py"
    initial = [
        GeneratedModule(generated_path, "generated v1\n"),
        GeneratedModule(public_path, "public scaffold\n", create_once=True),
    ]
    write(initial)
    public_path.write_text("hand-written customization\n")

    updated = [
        GeneratedModule(generated_path, "generated v2\n"),
        GeneratedModule(public_path, "new scaffold\n", create_once=True),
    ]
    write(updated)

    assert generated_path.read_text() == "generated v2\n"
    assert public_path.read_text() == "hand-written customization\n"
    assert all(is_current(module) for module in updated)


def test_docstrings_are_written_for_their_surface(spec: dict[str, Any]) -> None:
    """
    The reason endpoints are generated twice rather than desugared.

    A source transform rewrites code but never touches a docstring, which would leave the sync
    client documented as if it were asynchronous.
    """
    modules = render(spec)
    asynchronous = modules["_async/_generated/splits.py"]
    synchronous = modules["_sync/_generated/splits.py"]

    assert "Fetches every page asynchronously" in asynchronous
    assert "async with AsyncExampleApi(" in asynchronous
    assert "await api.splits_api.get_splits()" in asynchronous

    assert "Fetches every page, then validates" in synchronous
    assert "blocking" not in synchronous
    assert "with SyncExampleApi(" in synchronous
    assert "await" not in synchronous


def test_manifest_shapes_the_public_signature(spec: dict[str, Any]) -> None:
    """
    A wire parameter can surface under a Python-friendly name.

    `adjustment_type.any_of` is not a Python identifier and `adjustment_types: list[...]` is
    a usable argument name, so the manifest maps one onto the other.
    """
    source = render(spec)["_async/_generated/splits.py"]

    assert "adjustment_types: list[AdjustmentType] | None = None" in source
    assert 'coerce_choices(adjustment_types, AdjustmentType, "adjustment_types")' in source
    assert 'name="adjustment_type.any_of",' in source


def test_openapi_required_query_parameter_is_required_in_the_signature(spec: dict[str, Any]) -> None:
    """A required OpenAPI query parameter has no default and rejects a supplied None."""
    parameters = spec["paths"]["/stocks/v1/splits"]["get"]["parameters"]
    next(parameter for parameter in parameters if parameter["name"] == "execution_date.gte")["required"] = True

    source = render(spec)["_async/_generated/splits.py"]

    assert "execution_date_gte: str," in source
    assert "execution_date_gte: str | None = None" not in source
    assert 'name="execution_date.gte",' in source
    assert 'param_name="execution_date_gte"' in source


def test_manifest_cannot_weaken_an_openapi_required_parameter(spec: dict[str, Any]) -> None:
    """The OpenAPI document remains authoritative when it marks a parameter required."""
    parameters = spec["paths"]["/stocks/v1/splits"]["get"]["parameters"]
    next(parameter for parameter in parameters if parameter["name"] == "execution_date.gte")["required"] = True
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["params"]["execution_date.gte"] = {"required": False}

    source = render(spec, endpoints=endpoints)["_async/_generated/splits.py"]

    assert "execution_date_gte: str," in source
    assert "execution_date_gte: str | None = None" not in source


def test_openapi_parameter_sources_and_locations_are_honoured() -> None:
    """Path-item parameters, local refs and every supported wire location reach generated code."""
    spec = {
        "components": {
            "parameters": {
                "AccountId": {
                    "name": "account_id",
                    "in": "path",
                    "required": True,
                    "description": "Account to retrieve.",
                    "schema": {"type": "integer"},
                },
                "Workspace": {
                    "name": "X-Workspace-ID",
                    "in": "header",
                    "required": True,
                    "schema": {"type": "string"},
                },
            },
        },
        "paths": {
            "/v1/accounts/{account_id}": {
                "parameters": [
                    {"$ref": "#/components/parameters/AccountId"},
                    {
                        "name": "region",
                        "in": "query",
                        "required": True,
                        "description": "Region inherited from the path item.",
                        "schema": {"type": "string"},
                    },
                    {"$ref": "#/components/parameters/Workspace"},
                ],
                "get": {
                    "parameters": [
                        {
                            "name": "region",
                            "in": "query",
                            "description": "An operation-specific region filter.",
                            "schema": {"type": "boolean"},
                        },
                    ],
                },
            },
        },
    }
    endpoints = {
        "account": {
            "path": "/v1/accounts/{account_id}",
            "method_name": "get_account",
            "model": "Account",
            "shape": "single",
            "path_params": {"account_id": "account"},
            "params": {"X-Workspace-ID": {"name": "workspace_id"}},
        },
    }

    source = render(spec, endpoints=endpoints)["_async/_generated/account.py"]

    assert "account: int," in source
    assert "Account to retrieve." in source
    # The operation's declaration replaces the path-item version of the same query parameter.
    assert "region: bool | None = None" in source
    assert "An operation-specific region filter." in source
    assert "workspace_id: str," in source
    assert 'name="region",' in source
    assert '"X-Workspace-ID": require_value(workspace_id, "workspace_id"),' in source
    assert "headers=headers," in source


def test_openapi_cookie_parameters_are_rejected_until_supported() -> None:
    """Failing generation is safer than emitting an endpoint that silently drops a cookie."""
    spec = {
        "paths": {
            "/v1/accounts": {
                "get": {
                    "parameters": [
                        {"name": "session", "in": "cookie", "schema": {"type": "string"}},
                    ],
                },
            },
        },
    }
    endpoints = {
        "account": {
            "path": "/v1/accounts",
            "method_name": "get_account",
            "model": "Account",
            "shape": "single",
        },
    }

    with pytest.raises(ValueError, match="unsupported location 'cookie'"):
        render(spec, endpoints=endpoints)


def test_schema_less_content_parameter_is_skipped_like_upstream() -> None:
    """The parser follows upstream and skips parameters which do not carry ``schema``."""
    spec = {
        "paths": {
            "/v1/search": {
                "get": {
                    "parameters": [
                        {
                            "name": "filter",
                            "in": "query",
                            "content": {"application/json": {"schema": {"type": "object"}}},
                        },
                    ],
                },
            },
        },
    }
    endpoints = {
        "search": {
            "path": "/v1/search",
            "method_name": "search",
            "model": "SearchResult",
            "shape": "single",
        },
    }

    source = render(spec, endpoints=endpoints)["_async/_generated/search.py"]

    assert "filter:" not in source


def test_openapi_query_serialization_metadata_reaches_generated_code() -> None:
    """Array schemas and their OpenAPI style settings shape the generated request."""
    spec = {
        "paths": {
            "/v1/search": {
                "get": {
                    "parameters": [
                        {
                            "name": "symbol",
                            "in": "query",
                            "style": "form",
                            "explode": True,
                            "schema": {"type": "array", "items": {"type": "string"}},
                        },
                    ],
                },
            },
        },
    }
    endpoints = {
        "search": {
            "path": "/v1/search",
            "method_name": "search",
            "model": "SearchResult",
            "shape": "single",
        },
    }

    source = render(spec, endpoints=endpoints)["_async/_generated/search.py"]

    assert "symbol: list[str] | None = None" in source
    assert 'style="form"' in source
    assert "explode=True" in source


def test_manifest_uses_openapi_style_and_separate_coercion_style() -> None:
    """The manifest's `style` is wire serialization, not Spitzeisen coercion."""
    spec = {
        "paths": {
            "/v1/search": {
                "get": {
                    "parameters": [
                        {
                            "name": "symbol",
                            "in": "query",
                            "schema": {"type": "array", "items": {"type": "string"}},
                        },
                    ],
                },
            },
        },
    }
    endpoints = {
        "search": {
            "path": "/v1/search",
            "method_name": "search",
            "model": "SearchResult",
            "shape": "single",
            "params": {"symbol": {"style": "pipeDelimited", "explode": False}},
        },
    }

    source = render(spec, endpoints=endpoints)["_async/_generated/search.py"]

    assert 'style="pipeDelimited"' in source
    assert "explode=False" in source


def test_legacy_query_style_and_coercion_values_in_style_are_rejected() -> None:
    """The direct rename deliberately provides no manifest compatibility aliases."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["params"]["adjustment_type.any_of"] = {"query_style": "form"}

    with pytest.raises(ValidationError, match="query_style"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))

    endpoints["splits"]["params"]["adjustment_type.any_of"] = {"style": "comma_choice_list"}
    with pytest.raises(ValidationError, match="comma_choice_list"):
        Manifest.model_validate(manifest_dict(endpoints=endpoints))


def test_openapi_deep_object_query_serialization_is_rejected() -> None:
    """Do not generate an endpoint that would serialize deepObject incorrectly."""
    spec = {
        "paths": {
            "/v1/search": {
                "get": {
                    "parameters": [
                        {
                            "name": "filter",
                            "in": "query",
                            "style": "deepObject",
                            "schema": {
                                "type": "object",
                                "additionalProperties": {"type": "boolean"},
                            },
                        },
                    ],
                },
            },
        },
    }
    endpoints = {
        "search": {
            "path": "/v1/search",
            "method_name": "search",
            "model": "SearchResult",
            "shape": "single",
        },
    }

    with pytest.raises(ValueError, match="style 'deepObject' is unsupported"):
        render(spec, endpoints=endpoints)


def test_manifest_can_import_and_call_a_client_owned_coerce_function(spec: dict[str, Any]) -> None:
    """A client can apply vendor-specific parameter semantics without hand-writing an endpoint."""
    endpoints = manifest_dict()["endpoints"]
    parameter = endpoints["splits"]["params"]["adjustment_type.any_of"]
    parameter.update({"coercion_style": "plain", "coerce_function": "coerce_adjustment_types"})
    source = render(spec, endpoints=endpoints)["_async/_generated/splits.py"]

    assert "from example_api.params import coerce_adjustment_types" in source
    assert 'name="adjustment_type.any_of",' in source
    assert "coerce_adjustment_types(" in source
    assert 'param_name="adjustment_types",' in source
    assert "literal=AdjustmentType" in source


def test_parameter_overrides_must_exist_in_the_selected_operation(spec: dict[str, Any]) -> None:
    """A vendor removing a configured parameter is reported as manifest/spec drift."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["params"]["removed_filter"] = {"name": "removed_filter"}

    with pytest.raises(ValueError, match=r"removed_filter.*absent from the selected OpenAPI operation"):
        render(spec, endpoints=endpoints)


def test_dotted_filters_become_identifiers(spec: dict[str, Any]) -> None:
    """Filters the vendor names with dots still need to be callable arguments."""
    source = render(spec)["_async/_generated/splits.py"]

    assert "execution_date_gte: " in source
    assert 'name="execution_date.gte",' in source


def test_suffix_sort_style_strips_the_direction_from_the_default(spec: dict[str, Any]) -> None:
    """
    The vendor's default is `execution_date.desc`; the direction argument re-adds it.

    Carrying it through would send `execution_date.desc.desc`.
    """
    source = render(spec)["_async/_generated/splits.py"]

    assert 'sort: str = "execution_date"' in source
    assert "coerce_sort(sort, order)" in source
    assert 'name="sort"' in source


def test_a_separate_order_param_is_used_when_the_endpoint_has_one(spec: dict[str, Any]) -> None:
    """Not every endpoint encodes direction as a suffix; tickers takes a real `order`."""
    endpoints = {
        "tickers": {
            "path": "/v3/reference/tickers",
            "method_name": "get_all_tickers",
            "model": "Ticker",
            "pagination": "page_number",
            "sort_style": "param",
            "sort_param": "sort",
            "order_param": "order",
            "order_default": "asc",
        },
    }
    source = render(spec, endpoints=endpoints)["_async/_generated/tickers.py"]

    # Validated in place rather than combined into one value, which is the difference
    # between this style and the suffix one.
    assert 'order: Literal["asc", "desc"] = "asc"' in source
    assert 'coerce_choice(order, Literal["asc", "desc"], "order")' in source
    assert "Order" not in source
    assert "coerce_sort" not in source


def test_sorting_uses_explicit_wire_names_and_openapi_direction_values(spec: dict[str, Any]) -> None:
    """Neither query names nor the vendor's direction vocabulary are framework conventions."""
    parameters = spec["paths"]["/v3/reference/tickers"]["get"]["parameters"]
    sort_parameter = next(parameter for parameter in parameters if parameter["name"] == "sort")
    order_parameter = next(parameter for parameter in parameters if parameter["name"] == "order")
    sort_parameter["name"] = "order_by"
    order_parameter["name"] = "direction"
    order_parameter["schema"].update({"enum": ["up", "down"], "default": "up"})
    endpoints = {
        "tickers": {
            "path": "/v3/reference/tickers",
            "method_name": "get_all_tickers",
            "model": "Ticker",
            "pagination": "page_number",
            "sort_style": "param",
            "sort_param": "order_by",
            "order_param": "direction",
        },
    }

    source = render(spec, endpoints=endpoints)["_async/_generated/tickers.py"]

    assert 'order: Literal["up", "down"] = "up"' in source
    assert 'coerce_choice(order, Literal["up", "down"], "order")' in source
    assert 'name="order_by"' in source
    assert 'name="direction"' in source
    assert 'Literal["asc", "desc"]' not in source


def test_suffix_sorting_can_use_manifest_owned_literals_and_defaults(spec: dict[str, Any]) -> None:
    """A partial OpenAPI document can delegate closed sorting types to the client package."""
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"].update(
        {
            "sort_literal": "SortField",
            "order_literal": "SortDirection",
            "sort_default": "updated_at",
            "order_default": "down",
        },
    )

    source = render(spec, endpoints=endpoints)["_async/_generated/splits.py"]

    assert "from example_api.models import AdjustmentType, SortDirection, SortField" in source
    assert "from example_api.models.splits import Split" in source
    assert 'sort: SortField = "updated_at"' in source
    assert 'order: SortDirection = "down"' in source
    assert 'coerce_choice(sort, SortField, "sort")' in source
    assert 'coerce_choice(order, SortDirection, "order")' in source


def test_page_size_falls_back_to_the_spec(spec: dict[str, Any]) -> None:
    """
    The vendor states its own maximum; repeating it in the manifest invites drift.

    `/v3/reference/tickers` declares `limit.max: 1000` in its pagination extension.
    """
    endpoints = {
        "tickers": {
            "path": "/v3/reference/tickers",
            "method_name": "get_all_tickers",
            "model": "Ticker",
            "pagination": "page_number",
            "page_size_param": "limit",
        },
    }
    source = render(spec, endpoints=endpoints)["_async/_generated/tickers.py"]

    assert "max_page_size" not in source
    assert "min(max_results, 1000) if max_results is not None else 1000" in source
    assert 'name="limit"' in source


def test_page_size_parameter_name_is_explicit(spec: dict[str, Any]) -> None:
    """A vendor's `per_page` parameter is generated without assuming the name `limit`."""
    parameters = spec["paths"]["/stocks/v1/splits"]["get"]["parameters"]
    next(parameter for parameter in parameters if parameter["name"] == "limit")["name"] = "per_page"
    endpoints = manifest_dict()["endpoints"]
    endpoints["splits"]["page_size_param"] = "per_page"

    source = render(spec, endpoints=endpoints)["_async/_generated/splits.py"]

    assert 'name="per_page"' in source
    assert 'name="limit"' not in source


def test_scalar_cost_is_rendered(spec: dict[str, Any]) -> None:
    """The endpoint's scalar cost reaches the generated SpitzeisenEndpointSpec."""
    source = render(spec)["_async/_generated/splits.py"]

    assert "cost=1.0" in source


def single_endpoint(**overrides: Any) -> dict[str, Any]:
    """A single-resource lookup, the shape `not_found` applies to."""
    return {
        "station": {
            "path": "/v1/stations/{station_id}",
            "method_name": "get_station",
            "model": "Station",
            "shape": "single",
            **overrides,
        },
    }


def test_a_single_resource_lookup_raises_on_a_missing_resource_by_default() -> None:
    """
    A 404 says both "no such record" and "no such path", and only the vendor knows which.

    So the default is to raise: an endpoint whose path has gone stale must not read as a
    resource that happens not to exist.
    """
    source = render(None, endpoints=single_endpoint())["_async/_generated/station.py"]

    ast.parse(source)
    assert "-> Station:" in source
    assert "await self._request(" in source
    assert "_request_optional" not in source
    assert "NotFoundError: If the resource does not exist" in source


def test_declaring_not_found_empty_returns_none_instead() -> None:
    """The opt-in: `not_found: empty` is what makes an absent resource a return value."""
    source = render(None, endpoints=single_endpoint(not_found="empty"))["_async/_generated/station.py"]

    ast.parse(source)
    assert "-> Station | None:" in source
    assert "await self._request_optional(" in source
    assert "if raw is None:" in source


def test_not_found_is_independent_of_shape() -> None:
    """
    The point of the key: optionality is declared, not inferred from the return shape.

    Inferring it from `shape: single` would force None on single-resource lookups that want
    the exception, and deny it to collections that want an empty list.
    """
    optional = render(None, endpoints=single_endpoint(not_found="empty"))
    required = render(None, endpoints=single_endpoint())

    assert optional != required


def test_absent_as_empty_is_rejected_for_a_collection() -> None:
    """Nothing honours it on the pagination path yet, and a key that silently does nothing is worse."""
    with pytest.raises(ValidationError, match="only supported for shape='single'"):
        Manifest.model_validate(manifest_dict(endpoints=single_endpoint(shape="collection", not_found="empty")))


def test_a_single_resource_endpoint_without_an_envelope_returns_the_body() -> None:
    """`results_key: null` means the body *is* the object, which many APIs do."""
    endpoints = single_endpoint(results_key=None)
    source = render(None, endpoints=endpoints)["_async/_generated/station.py"]

    ast.parse(source)
    assert "if not isinstance(data, dict):" in source
    assert "raise ResponseShapeError(msg)" in source
    assert "data.get(" not in source
    assert "return data" in source


def test_openapi_parameters_feed_the_same_policy_pipeline() -> None:
    """OpenAPI owns wire parameters while the manifest owns friendly SDK presentation."""
    endpoints = {
        "strikes": {
            "path": "/datav2/strikes",
            "method_name": "get_strikes",
            "model": "Strike",
            "pagination": "none",
            "params": {
                "ticker": {"description": "Ticker to fetch strikes for.", "required": True},
                "tradeDate": {"name": "trade_date", "coercion_style": "date"},
                "workspace": {"required": True},
            },
        },
    }
    spec = {
        "paths": {
            "/datav2/strikes": {
                "get": {
                    "parameters": [
                        {"name": "ticker", "in": "query", "schema": {"type": "string"}},
                        {"name": "tradeDate", "in": "query", "schema": {"type": "string", "format": "date"}},
                        {"name": "workspace", "in": "header", "schema": {"type": "string"}},
                    ],
                    "responses": {"200": {"description": "OK"}},
                },
            },
        },
    }

    modules = render(spec, endpoints=endpoints)
    source = modules["_async/_generated/strikes.py"]

    ast.parse(source)
    assert "ticker: str," in source
    assert "ticker: str | None = None" not in source
    assert "trade_date: str | date | datetime | None = None" in source
    assert 'coerce_date(trade_date, "trade_date")' in source
    assert "Ticker to fetch strikes for." in source
    assert '"workspace": require_value(workspace, "workspace")' in source


def test_generated_client_runs_against_the_runtime(spec: dict[str, Any], tmp_path: Path) -> None:
    """
    The acceptance test for the whole pipeline: generated code has to *work*.

    Writes a real package, imports it, and drives it through the scripted transport — so a
    template that produces plausible-looking but wrong code fails here rather than in a client
    repo weeks later.
    """
    package = tmp_path / "example_api"
    (package / "_async" / "_generated").mkdir(parents=True)
    (package / "__init__.py").write_text("")
    (package / "_async" / "__init__.py").write_text("")
    (package / "_async" / "_generated" / "__init__.py").write_text("")
    (package / "params.py").write_text(
        "from collections.abc import Sequence\n"
        "from typing import Any\n"
        "from spitzeisen import coerce_choices\n"
        "def coerce_adjustment_types(\n"
        "    values: Sequence[str] | None, *, param_name: str, literal: Any | None\n"
        ") -> str | None:\n"
        "    return coerce_choices(values, literal, param_name)\n",
    )
    (package / "models").mkdir()
    (package / "models" / "_generated.py").write_text(
        "from typing import Literal\n"
        "from datetime import date\n"
        "from spitzeisen import SpitzeisenModel\n"
        "class Split(SpitzeisenModel):\n"
        "    ticker: str\n"
        "    execution_date: date\n"
        '    adjustment_type: Literal["forward_split", "reverse_split", "stock_dividend"]\n',
    )
    (package / "models" / "__init__.py").write_text(
        'from typing import Literal\nAdjustmentType = Literal["forward_split", "reverse_split", "stock_dividend"]\n',
    )
    endpoints = manifest_dict()["endpoints"]
    parameter = endpoints["splits"]["params"]["adjustment_type.any_of"]
    parameter.update({"coercion_style": "plain", "coerce_function": "coerce_adjustment_types"})
    endpoints["splits"]["params"]["ticker"] = {"required": True}
    for name, source in render(spec, endpoints=endpoints).items():
        if name.startswith("_async/") or name == "models/splits.py":
            target = package / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(source)

    sys.path.insert(0, str(tmp_path))
    try:
        generated: Any = importlib.import_module("example_api._async.client")

        router = FakeRouter().add_pages(
            "/stocks/v1/splits",
            [[{"ticker": "AAPL", "execution_date": "2020-08-31", "adjustment_type": "forward_split"}]],
        )
        api = generated.AsyncExampleApi(
            AsyncSpitzeisenConfig(
                base_url="https://api.example.test",
                http_client=httpx2.AsyncClient(transport=router.mock_transport()),
                limiter=NoLimit(),
            ),
        )

        async def exercise_public_client() -> list[Any]:
            async with api:
                with pytest.raises(ValueError, match=r"Required parameter 'ticker' was not provided"):
                    await api.splits_api.get_splits(ticker=None, adjustment_types=["forward_split"])
                assert router.requests == []
                return await api.splits_api.get_splits(ticker="AAPL", adjustment_types=["forward_split"])

        records = asyncio.run(exercise_public_client())
    finally:
        sys.path.remove(str(tmp_path))
        for module_name in list(sys.modules):
            if module_name == "example_api" or module_name.startswith("example_api."):
                sys.modules.pop(module_name, None)

    assert [record.ticker for record in records] == ["AAPL"]
    assert records[0].execution_date == date(2020, 8, 31)
    assert len(router.requests) == 2  # The page-number strategy requests its empty terminal page.
    # The manifest's comma_choice_list shaping reached the wire under the vendor's own parameter name.
    assert router.requests[0].params["adjustment_type.any_of"] == "forward_split"
    assert router.requests[0].params["sort"] == "execution_date.desc"
