"""
Generated awaitable WeatherApi client wiring.

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; add client-specific behaviour
to the public subclass beside the `_generated` package.
"""

from typing import TYPE_CHECKING, Self

from weather_sdk._async.current_weather import AsyncCurrentWeatherApi

if TYPE_CHECKING:
    from spitzeisen import AsyncSpitzeisenConfig


class AsyncWeatherApiBase:
    """Own and share one configuration across every generated endpoint API."""

    def __init__(self, config: AsyncSpitzeisenConfig) -> None:
        """Build every endpoint API around the same connection-level configuration."""
        self.config = config

        self.current_weather_api = AsyncCurrentWeatherApi(config)

        self._endpoint_apis = (self.current_weather_api,)

    async def __aenter__(self) -> Self:
        """Enter every endpoint API while sharing one lazily-created HTTP client."""
        for endpoint_api in self._endpoint_apis:
            await endpoint_api.__aenter__()
        return self

    async def __aexit__(self, *args: object) -> None:
        """Exit every endpoint API and close an owned HTTP client after the last holder."""
        for endpoint_api in reversed(self._endpoint_apis):
            await endpoint_api.__aexit__(*args)
