"""
Generated asynchronous WeatherApi client wiring.

Generated by spitzeisen-gen from the assembled Smithy model. Do not edit; add client-specific behaviour
to the public subclass beside the `_generated` package.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Self

from weather_sdk._async.current_weather import AsyncCurrentWeatherApi

if TYPE_CHECKING:
    from spitzeisen import AsyncSpitzeisenConfig


class AsyncWeatherApiBase:
    """Own and share one configuration across every generated operation API."""

    def __init__(self, config: AsyncSpitzeisenConfig) -> None:
        """Build every operation API around the same connection-level configuration."""
        self.config = config

        self.current_weather_api = AsyncCurrentWeatherApi(config)

        self._operation_apis = (self.current_weather_api,)

    async def __aenter__(self) -> Self:
        """Enter every operation API while sharing one lazily-created HTTP client."""
        for operation_api in self._operation_apis:
            await operation_api.__aenter__()
        return self

    async def __aexit__(self, *args: object) -> None:
        """Exit every operation API and close an owned HTTP client after the last holder."""
        for operation_api in reversed(self._operation_apis):
            await operation_api.__aexit__(*args)
