# Generated by spitzeisen-gen.
from __future__ import annotations

from typing import Self

from spitzeisen import AsyncSpitzeisenConfig  # noqa: TC001 - retain runtime annotation introspection
from weather_sdk._async.current_weather import AsyncCurrentWeatherApi


class AsyncWeatherApiBase:
    """Client for openweathermap. Shares one configuration across operation APIs."""

    def __init__(self, config: AsyncSpitzeisenConfig) -> None:
        """Build all operation APIs around the supplied configuration."""
        self.config = config
        self.current_weather_api = AsyncCurrentWeatherApi(config)
        self._operation_apis = (self.current_weather_api,)

    async def __aenter__(self) -> Self:
        """Enter each API while sharing one lazily-created HTTP client."""
        for operation_api in self._operation_apis:
            await operation_api.__aenter__()
        return self

    async def __aexit__(self, *args: object) -> None:
        """Release each API and close the shared owned client after its last holder."""
        for operation_api in reversed(self._operation_apis):
            await operation_api.__aexit__(*args)
