"""
Current Weather operation (async).

Generated by spitzeisen-gen from the assembled Smithy model. Do not edit; run `mise run codegen`.
Vendor documentation: https://openweathermap.org/api/current?collection=current_forecast
"""

from __future__ import annotations

from typing import Any, Literal

from spitzeisen import (
    AsyncSpitzeisenApi,
    NoPagination,
    ResponseShapeError,
    SpitzeisenOperationSpec,
    build_header_params,
    serialize_query_param,
)
from weather_sdk.models.current_weather import CurrentWeatherResponse

CURRENT_WEATHER_OPERATION = SpitzeisenOperationSpec(
    path="/data/2.5/weather",
    cost=1.0,
    pagination=NoPagination(results_key=None),
)


class AsyncCurrentWeatherApiBase(AsyncSpitzeisenApi):
    """
    Generated request layer for the current weather operation.

    Subclassed by `AsyncCurrentWeatherApi`, which is where any hand-written behaviour
    belongs - this class is regenerated and never edited.
    """

    async def get_current_weather_raw(
        self,
        *,
        latitude: float,
        longitude: float,
        units: Literal["standard", "metric", "imperial"] = "standard",
        language: str | None = None,
    ) -> dict[str, Any] | None:
        """
        Fetch the raw JSON object, without validation.

        Returns None when the resource does not exist (HTTP 404), which this operation treats
        as a routine outcome rather than a failure.
        """
        latitude = self._validate_input(latitude, float)
        longitude = self._validate_input(longitude, float)
        units = self._validate_input(units, Literal["standard", "metric", "imperial"])
        language = self._validate_input(language, str | None)
        params = [
            *serialize_query_param(
                latitude,
                name="lat",
                style="form",
                explode=False,
                required=True,
                param_name="latitude",
            ),
            *serialize_query_param(
                longitude,
                name="lon",
                style="form",
                explode=False,
                required=True,
                param_name="longitude",
            ),
            *serialize_query_param(
                units,
                name="units",
                style="form",
                explode=False,
                required=False,
                param_name="units",
            ),
            *serialize_query_param(
                language,
                name="lang",
                style="form",
                explode=False,
                required=False,
                param_name="language",
            ),
        ]
        headers = build_header_params(
            {},
        )
        data = await self._request_optional(
            CURRENT_WEATHER_OPERATION,
            params=params,
            headers=headers,
        )
        if data is None:
            return None
        if not isinstance(data, dict):
            msg = "expected the current weather response body to be an object"
            raise ResponseShapeError(msg)
        # No envelope: the body is the object.
        return data

    async def get_current_weather(
        self,
        *,
        latitude: float,
        longitude: float,
        units: Literal["standard", "metric", "imperial"] = "standard",
        language: str | None = None,
    ) -> CurrentWeatherResponse | None:
        """
        Returns the current weather observation for one latitude and longitude.

        Fetches the response asynchronously, then validates it.

        Docs: https://openweathermap.org/api/current?collection=current_forecast

        Example::

            async with AsyncWeatherApi(config) as api:
                result = await api.current_weather_api.get_current_weather(latitude=..., longitude=...)

        Args:
            latitude: Latitude of the location.
            longitude: Longitude of the location.
            units: Units of measurement. Standard units are used by default.
            language: Language code used for the city name and weather description.

        Returns:
            A validated `CurrentWeatherResponse`, or None when the resource does not exist (HTTP 404).

        Raises:
            pydantic.ValidationError: If the response payload does not match.


        """
        raw = await self.get_current_weather_raw(
            latitude=latitude,
            longitude=longitude,
            units=units,
            language=language,
        )
        if raw is None:
            return None
        return CurrentWeatherResponse.model_validate(raw)
