"""
Current Weather endpoint (async).

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; run `mise run codegen`.

Vendor documentation: https://openweathermap.org/api/current?collection=current_forecast

"""

from __future__ import annotations

from typing import Any, Literal

from spitzeisen import (
    AsyncSpitzeisenApi,
    NoPagination,
    ResponseShapeError,
    SpitzeisenEndpointSpec,
    build_header_params,
    serialize_query_param,
)
from weather_sdk.models.current_weather import CurrentWeatherResponse

CURRENT_WEATHER_ENDPOINT = SpitzeisenEndpointSpec(
    path="/data/2.5/weather",
    cost=1.0,
    pagination=NoPagination(results_key=None),
)


class AsyncCurrentWeatherApiBase(AsyncSpitzeisenApi):
    """
    Generated request layer for the current weather endpoint.

    Subclassed by `AsyncCurrentWeatherApi`, which is where any hand-written behaviour
    belongs — this class is regenerated and never edited.
    """

    async def get_current_weather_raw(
        self,
        *,
        latitude: float,
        longitude: float,
        units: Literal["standard", "metric", "imperial"] = "standard",
        language: str | None = None,
    ) -> dict[str, Any]:
        """
        Fetch the raw JSON object, without validation.

        A missing resource raises `NotFoundError` like any other error status; this endpoint
        does not declare `not_found: empty`.
        """
        params = [
            *serialize_query_param(
                latitude,
                name="lat",
                style="form",
                explode=False,
                required=True,
                param_name="latitude",
            ),
            *serialize_query_param(
                longitude,
                name="lon",
                style="form",
                explode=False,
                required=True,
                param_name="longitude",
            ),
            *serialize_query_param(
                units,
                name="units",
                style="form",
                explode=False,
                required=False,
                param_name="units",
            ),
            *serialize_query_param(
                language,
                name="lang",
                style="form",
                explode=False,
                required=False,
                param_name="language",
            ),
        ]
        headers = build_header_params(
            {},
        )
        data = await self._request(
            CURRENT_WEATHER_ENDPOINT,
            params,
            headers=headers,
        )
        if not isinstance(data, dict):
            msg = "expected the current weather response body to be an object"
            raise ResponseShapeError(msg)
        # No envelope: the body is the object.
        return data

    async def get_current_weather(
        self,
        *,
        latitude: float,
        longitude: float,
        units: Literal["standard", "metric", "imperial"] = "standard",
        language: str | None = None,
    ) -> CurrentWeatherResponse:
        """
        Fetch the current weather observation for one location.

        Fetches the response asynchronously, then validates it.

        Docs: https://openweathermap.org/api/current?collection=current_forecast

        Example::

            async with AsyncWeatherApi(config) as api:
                result = await api.current_weather_api.get_current_weather(latitude=..., longitude=...)

        Args:
            latitude: Latitude of the location.
            longitude: Longitude of the location.
            units: Units of measurement. Standard units are used by default.
            language: Language code used for the city name and weather description.

        Returns:
            A validated `CurrentWeatherResponse`.

        Raises:
            pydantic.ValidationError: If the response payload does not match.

            NotFoundError: If the resource does not exist (HTTP 404).

        """
        raw = await self.get_current_weather_raw(
            latitude=latitude,
            longitude=longitude,
            units=units,
            language=language,
        )
        return CurrentWeatherResponse.model_validate(raw)
