# Generated by datamodel-code-generator from the assembled Smithy model.

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from spitzeisen import SpitzeisenModel
from spitzeisen.models import response_constraints as _spitzeisen_response_constraints


class Clouds(SpitzeisenModel):
    all: Annotated[int, Field(alias="all"), _spitzeisen_response_constraints(ge=0, le=100)]
    """
    Cloudiness percentage.
    """


class Coordinates(SpitzeisenModel):
    lat: Annotated[float, Field(alias="lat"), _spitzeisen_response_constraints(ge=-90.0, le=90.0)]
    """
    Latitude of the location.
    """
    lon: Annotated[float, Field(alias="lon"), _spitzeisen_response_constraints(ge=-180.0, le=180.0)]
    """
    Longitude of the location.
    """


class PrecipitationVolume(SpitzeisenModel):
    n1h: Annotated[float, Field(alias="1h")]
    """
    Precipitation volume for the preceding hour in mm/h.
    """


class SystemMetadata(SpitzeisenModel):
    type_: Annotated[int | None, Field(alias="type")] = None
    """
    Internal parameter.
    """
    country: Annotated[str, Field(alias="country")]
    """
    Country code.
    """
    id: Annotated[int | None, Field(alias="id")] = None
    """
    Internal parameter.
    """
    message: Annotated[float | None, Field(alias="message")] = None
    """
    Internal parameter present in some responses.
    """
    sunrise: Annotated[int, Field(alias="sunrise")]
    """
    Sunrise time as a Unix timestamp in UTC.
    """
    sunset: Annotated[int, Field(alias="sunset")]
    """
    Sunset time as a Unix timestamp in UTC.
    """


class WeatherCondition(SpitzeisenModel):
    description: Annotated[str, Field(alias="description")]
    """
    Weather condition within the group.
    """
    icon: Annotated[str, Field(alias="icon")]
    """
    Weather icon identifier.
    """
    id: Annotated[int, Field(alias="id")]
    """
    Weather condition identifier.
    """
    main: Annotated[str, Field(alias="main")]
    """
    Weather condition group, such as Rain, Snow, or Clouds.
    """


class WeatherMeasurements(SpitzeisenModel):
    feels_like: Annotated[float, Field(alias="feels_like")]
    """
    Temperature adjusted for human perception.
    """
    grnd_level: Annotated[int | None, Field(alias="grnd_level")] = None
    """
    Atmospheric pressure at ground level in hPa, where available.
    """
    humidity: Annotated[int, Field(alias="humidity"), _spitzeisen_response_constraints(ge=0, le=100)]
    """
    Humidity percentage.
    """
    pressure: Annotated[int, Field(alias="pressure")]
    """
    Atmospheric pressure at sea level in hPa.
    """
    sea_level: Annotated[int | None, Field(alias="sea_level")] = None
    """
    Atmospheric pressure at sea level in hPa, where available.
    """
    temp: Annotated[float, Field(alias="temp")]
    """
    Current temperature.
    """
    temp_max: Annotated[float | None, Field(alias="temp_max")] = None
    """
    Optional maximum currently observed temperature within the location.
    """
    temp_min: Annotated[float | None, Field(alias="temp_min")] = None
    """
    Optional minimum currently observed temperature within the location.
    """


class Wind(SpitzeisenModel):
    deg: Annotated[int, Field(alias="deg")]
    """
    Meteorological wind direction in degrees.
    """
    gust: Annotated[float | None, Field(alias="gust")] = None
    """
    Wind gust speed, where available.
    """
    speed: Annotated[float, Field(alias="speed")]
    """
    Wind speed in units selected by the request.
    """


class CurrentWeatherResponse(SpitzeisenModel):
    base: Annotated[str | None, Field(alias="base")] = None
    """
    Internal parameter.
    """
    clouds: Annotated[Clouds | None, Field(alias="clouds")] = None
    cod: Annotated[int, Field(alias="cod")]
    """
    Internal response status code.
    """
    coord: Annotated[Coordinates, Field(alias="coord")]
    dt: Annotated[int, Field(alias="dt")]
    """
    Time of data calculation as a Unix timestamp in UTC.
    """
    id: Annotated[int, Field(alias="id")]
    """
    City identifier.
    """
    main: Annotated[WeatherMeasurements, Field(alias="main")]
    name: Annotated[str, Field(alias="name")]
    """
    City name.
    """
    rain: Annotated[PrecipitationVolume | None, Field(alias="rain")] = None
    snow: Annotated[PrecipitationVolume | None, Field(alias="snow")] = None
    sys: Annotated[SystemMetadata | None, Field(alias="sys")] = None
    timezone: Annotated[int, Field(alias="timezone")]
    """
    Shift in seconds from UTC.
    """
    visibility: Annotated[int | None, Field(alias="visibility")] = None
    """
    Visibility in metres, with a maximum reported value of 10 km.
    """
    weather: Annotated[list[WeatherCondition], Field(alias="weather")]
    wind: Annotated[Wind | None, Field(alias="wind")] = None
