# Generated by datamodel-code-generator from selected OpenAPI operations.

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from spitzeisen import SpitzeisenModel


class Clouds(SpitzeisenModel):
    all: Annotated[int, Field(ge=0, le=100)]
    """
    Cloudiness percentage.
    """


class Coordinates(SpitzeisenModel):
    lon: Annotated[float, Field(ge=-180.0, le=180.0)]
    """
    Longitude of the location.
    """
    lat: Annotated[float, Field(ge=-90.0, le=90.0)]
    """
    Latitude of the location.
    """


class PrecipitationVolume(SpitzeisenModel):
    field_1h: Annotated[float, Field(alias="1h")]
    """
    Precipitation volume for the preceding hour in mm/h.
    """


class SystemMetadata(SpitzeisenModel):
    type: int | None = None
    """
    Internal parameter.
    """
    id: int | None = None
    """
    Internal parameter.
    """
    message: float | None = None
    """
    Internal parameter present in some responses.
    """
    country: str
    """
    Country code.
    """
    sunrise: int
    """
    Sunrise time as a Unix timestamp in UTC.
    """
    sunset: int
    """
    Sunset time as a Unix timestamp in UTC.
    """


class WeatherCondition(SpitzeisenModel):
    id: int
    """
    Weather condition identifier.
    """
    main: str
    """
    Weather condition group, such as Rain, Snow, or Clouds.
    """
    description: str
    """
    Weather condition within the group.
    """
    icon: str
    """
    Weather icon identifier.
    """


class WeatherMeasurements(SpitzeisenModel):
    temp: float
    """
    Current temperature.
    """
    feels_like: float
    """
    Temperature adjusted for human perception.
    """
    temp_min: float | None = None
    """
    Optional minimum currently observed temperature within the location.
    """
    temp_max: float | None = None
    """
    Optional maximum currently observed temperature within the location.
    """
    pressure: int
    """
    Atmospheric pressure at sea level in hPa.
    """
    humidity: Annotated[int, Field(ge=0, le=100)]
    """
    Humidity percentage.
    """
    sea_level: int | None = None
    """
    Atmospheric pressure at sea level in hPa, where available.
    """
    grnd_level: int | None = None
    """
    Atmospheric pressure at ground level in hPa, where available.
    """


class Wind(SpitzeisenModel):
    speed: float
    """
    Wind speed in units selected by the request.
    """
    deg: int
    """
    Meteorological wind direction in degrees.
    """
    gust: float | None = None
    """
    Wind gust speed, where available.
    """


class CurrentWeatherResponse(SpitzeisenModel):
    coord: Coordinates
    weather: list[WeatherCondition]
    base: str | None = None
    """
    Internal parameter.
    """
    main: WeatherMeasurements
    visibility: int | None = None
    """
    Visibility in metres, with a maximum reported value of 10 km.
    """
    wind: Wind | None = None
    rain: PrecipitationVolume | None = None
    snow: PrecipitationVolume | None = None
    clouds: Clouds | None = None
    dt: int
    """
    Time of data calculation as a Unix timestamp in UTC.
    """
    sys: SystemMetadata | None = None
    timezone: int
    """
    Shift in seconds from UTC.
    """
    id: int
    """
    City identifier.
    """
    name: str
    """
    City name.
    """
    cod: int
    """
    Internal response status code.
    """
