"""The ``spitzeisen-gen`` command-line interface."""

from __future__ import annotations

import codecs
import json
import os
import re
import shutil
import subprocess
import tempfile
import zipfile
from collections.abc import Generator, Sequence
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from pprint import pformat
from typing import TYPE_CHECKING, Any, cast

import typer

from spitzeisen.codegen.assembly import assemble_smithy
from spitzeisen.codegen.exceptions import CodegenError
from spitzeisen.codegen.generate import (
    GeneratedModule,
    formatted_module,
    generated_model_names,
    model_exports_module,
    python_tool,
)
from spitzeisen.codegen.inputs import load_compile_inputs, load_document
from spitzeisen.codegen.java_frontend import PLUGIN_JAR
from spitzeisen.codegen.model_validation import runtime_response_constraints
from spitzeisen.codegen.openapi import import_openapi
from spitzeisen.codegen.toolchain import ALLOY_VERSION, JAVA_VERSION, SMITHY_VERSION

if TYPE_CHECKING:
    from spitzeisen.codegen.artifacts import ArtifactManifest
    from spitzeisen.codegen.diagnostics import ModelImportWarning

DEFAULT_MODEL_BASE_CLASS = "spitzeisen.SpitzeisenModel"
DEFAULT_HTTP_TIMEOUT = 5
MODEL_HEADER = re.compile(
    r"\A# generated by datamodel-codegen:\r?\n#\s+filename:\s+(?P<filename>[^\r\n]+)\r?\n",
)


@dataclass(frozen=True, slots=True)
class Config:
    """Resolved command-line configuration."""

    source: str | Path | None
    smithy_sources: tuple[Path, ...]
    overlays: tuple[Path, ...]
    service: str | None
    package: str
    client_name: str
    vendor: str | None
    python_settings_path: Path | None
    output_path: Path
    file_encoding: str
    base_class: str
    http_timeout: int
    require_api_required_arguments: bool | None = None


@dataclass(frozen=True, slots=True)
class RenderResult:
    """Rendered modules and non-fatal model-import warnings."""

    modules: list[GeneratedModule]
    warnings: tuple[ModelImportWarning, ...]


@dataclass(frozen=True, slots=True)
class DoctorCheck:
    """One local code-generation prerequisite checked by ``spitzeisen-gen doctor``."""

    label: str
    passed: bool
    detail: str


main = typer.Typer(name="spitzeisen-gen", no_args_is_help=True)


@main.callback()
def cli() -> None:
    """Generate a polished Python SDK from Smithy or imported OpenAPI."""


def _command_output(command: list[str]) -> tuple[bool, str]:
    """Run one cheap version command without turning diagnostics into tracebacks."""
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=False, timeout=5)  # noqa: S603
    except OSError as err:
        return False, str(err)
    output = (result.stdout or result.stderr).strip()
    return result.returncode == 0, output


def _doctor_checks() -> tuple[DoctorCheck, ...]:
    """Check local launch prerequisites without downloading dependencies or invoking Smithy."""
    java = shutil.which("java")
    if java is None:
        java_check = DoctorCheck("Java", False, f"not found (requires Java {JAVA_VERSION} or newer)")
    else:
        available, output = _command_output([java, "-version"])
        match = re.search(r'version\s+"(?P<major>\d+)', output)
        major = int(match.group("major")) if match else None
        java_check = DoctorCheck(
            "Java",
            available and major is not None and major >= JAVA_VERSION,
            (
                f"{output.splitlines()[0]} (requires Java {JAVA_VERSION} or newer)"
                if output
                else f"could not read the Java version (requires Java {JAVA_VERSION} or newer)"
            ),
        )

    coursier = shutil.which("coursier") or shutil.which("cs")
    if coursier is None:
        coursier_check = DoctorCheck("Coursier", False, "not found (install `coursier` or `cs` on PATH)")
    else:
        available, output = _command_output([coursier, "version"])
        coursier_check = DoctorCheck(
            "Coursier",
            available,
            output.splitlines()[0] if output else f"{coursier} did not report a version",
        )

    try:
        with zipfile.ZipFile(PLUGIN_JAR) as bundle:
            required_entries = {
                "META-INF/services/software.amazon.smithy.build.SmithyBuildPlugin",
                "META-INF/smithy/spitzeisen-api.smithy",
                "META-INF/smithy/spitzeisen-python.smithy",
            }
            has_traits = required_entries.issubset(bundle.namelist())
        bundle_check = DoctorCheck(
            "Bundled Smithy plugin",
            has_traits,
            f"{PLUGIN_JAR} ({'includes' if has_traits else 'is missing'} custom traits)",
        )
    except (OSError, zipfile.BadZipFile) as err:
        bundle_check = DoctorCheck("Bundled Smithy plugin", False, f"{PLUGIN_JAR}: {err}")

    smithy_check = DoctorCheck(
        "Smithy",
        True,
        f"pinned CLI and JSON Schema frontend {SMITHY_VERSION}; Alloy {ALLOY_VERSION}",
    )
    return java_check, coursier_check, bundle_check, smithy_check


@main.command()
def doctor() -> None:
    """Check the local Java, Coursier, and bundled Smithy frontend prerequisites."""
    checks = _doctor_checks()
    for check in checks:
        status = "OK" if check.passed else "FAIL"
        typer.secho(
            f"{status:4} {check.label}: {check.detail}",
            fg=typer.colors.GREEN if check.passed else typer.colors.RED,
        )
    if not all(check.passed for check in checks):
        raise typer.Exit(code=1)


def _select_source(url: str | None, path: Path | None) -> str | Path:
    """Resolve mutually exclusive OpenAPI source options."""
    if url and not path:
        return url
    if path and not url:
        return path
    if url and path:
        message = "provide either --url or --path, not both"
        raise typer.BadParameter(message, param_hint="--url / --path")
    message = "provide either --url or --path"
    raise typer.BadParameter(message, param_hint="--url / --path")


def _select_generation_source(
    url: str | None,
    path: Path | None,
    smithy: list[Path] | None,
) -> tuple[str | Path | None, tuple[Path, ...]]:
    """Resolve one native Smithy source set or one OpenAPI source."""
    smithy_sources = tuple(smithy or ())
    if smithy_sources:
        if url or path:
            message = "provide native --smithy sources or an OpenAPI --url/--path, not both"
            raise typer.BadParameter(message, param_hint="--smithy / --url / --path")
        return None, smithy_sources
    if not url and not path:
        message = "provide --smithy, --url, or --path"
        raise typer.BadParameter(message, param_hint="--smithy / --url / --path")
    return _select_source(url, path), ()


def _process_config(  # noqa: PLR0913 - mirrors the public Typer options
    *,
    url: str | None,
    path: Path | None,
    smithy: list[Path] | None,
    overlays: list[Path] | None,
    service: str | None,
    package: str,
    client_name: str,
    vendor: str | None,
    python_settings_path: Path | None,
    output_path: Path,
    file_encoding: str,
    base_class: str,
    http_timeout: int,
    require_api_required_arguments: bool | None = None,
) -> Config:
    """Validate command options and resolve the selected document source."""
    source, smithy_sources = _select_generation_source(url, path, smithy)
    try:
        codecs.getencoder(file_encoding)
    except LookupError as err:
        message = f"unknown encoding: {file_encoding}"
        raise typer.BadParameter(message, param_hint="--file-encoding") from err
    return Config(
        source=source,
        smithy_sources=smithy_sources,
        overlays=tuple(overlays or ()),
        service=service,
        package=package,
        client_name=client_name,
        vendor=vendor,
        python_settings_path=python_settings_path,
        output_path=output_path,
        file_encoding=file_encoding,
        base_class=base_class,
        http_timeout=http_timeout,
        require_api_required_arguments=require_api_required_arguments,
    )


def _print_import_warning(err: ModelImportWarning) -> None:
    """Print one recoverable model-import warning."""
    color = typer.colors.YELLOW
    typer.secho(err.header, bold=True, fg=color, err=True)
    typer.echo(err=True)
    if err.detail:
        typer.secho(err.detail, fg=color, err=True)
        typer.echo(err=True)
    if err.data is not None:
        typer.secho(pformat(err.data), fg=color, err=True)
    typer.echo(err=True)


def handle_warnings(warnings: Sequence[ModelImportWarning], fail_on_warning: bool = False) -> None:
    """Render import and compatibility diagnostics and optionally fail the command."""
    if not warnings:
        return
    message = "Generation warnings: review the import or compatibility diagnostics below."
    typer.secho(message, underline=True, bold=True, fg=typer.colors.BRIGHT_YELLOW, err=True)
    typer.echo(err=True)
    for warning in warnings:
        _print_import_warning(warning)
    _print_issue_link()
    if fail_on_warning:
        raise typer.Exit(code=1)


def _print_issue_link() -> None:
    """Print the project issue link after an expected generation problem."""
    issue_link = typer.style(
        "https://github.com/feuerstein-org/spitzeisen/issues/new/choose",
        fg=typer.colors.BRIGHT_BLUE,
    )
    typer.secho(
        "If you believe this was a mistake or this tool is missing a feature you need, "
        f"please open an issue at {issue_link}",
        fg=typer.colors.BLUE,
        err=True,
    )


@contextmanager
def _handle_codegen_errors() -> Generator[None]:
    """Turn expected fatal failures into concise CLI output at the outer boundary."""
    try:
        yield
    except CodegenError as err:
        typer.secho(err.header, bold=True, fg=typer.colors.BRIGHT_RED, err=True)
        if err.detail:
            typer.echo(err=True)
            typer.secho(err.detail, fg=typer.colors.RED, err=True)
        typer.echo(err=True)
        _print_issue_link()
        raise typer.Exit(code=1) from err


@main.command("import-openapi")
def import_openapi_command(
    url: str | None = typer.Option(None, help="A URL to read the OpenAPI document from"),
    path: Path | None = typer.Option(None, help="A path to the OpenAPI document"),
    output_path: Path = typer.Option(..., help="Destination for the Smithy 2.0 JSON AST"),
    overlay: list[Path] | None = typer.Option(None, "--overlay", help="Smithy overlay file; may be repeated"),
    http_timeout: int = typer.Option(DEFAULT_HTTP_TIMEOUT, min=1, help="OpenAPI URL timeout in seconds"),
) -> None:
    """Import OpenAPI into the pinned, inspectable Smithy JSON representation."""
    source = _select_source(url, path)
    with _handle_codegen_errors():
        spec = load_document(source=source, timeout=http_timeout)
        imported = import_openapi(spec, working_directory=output_path.parent)
        model = assemble_smithy(imported.model, tuple(overlay or ()), working_directory=output_path.parent)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with _temporary_sibling(output_path, suffix=".json") as temporary:
        temporary.write_text(json.dumps(model, indent=2) + "\n")
        temporary.replace(output_path)
    typer.echo(f"wrote Smithy JSON AST: {output_path}")
    handle_warnings(imported.warnings)


@main.command()
def generate(  # noqa: PLR0913, PLR0917 - Typer exposes each CLI option as a parameter
    url: str | None = typer.Option(None, help="A URL to read the OpenAPI document from"),
    path: Path | None = typer.Option(None, help="A path to the OpenAPI document"),
    smithy: list[Path] | None = typer.Option(None, "--smithy", help="Native Smithy source; may be repeated"),
    overlay: list[Path] | None = typer.Option(None, "--overlay", help="Smithy overlay file; may be repeated"),
    service: str | None = typer.Option(None, help="Smithy service shape ID; inferred when the model has one service"),
    package: str = typer.Option(..., help="Importable Python package name"),
    client_name: str = typer.Option(..., help="Generated aggregate client class name"),
    vendor: str | None = typer.Option(None, help="Readable vendor name used in generated documentation"),
    python_settings: Path | None = typer.Option(
        None,
        "--python-settings",
        help="JSON file containing Python generation policies, external models, adapters, and protocol preferences",
    ),
    output_path: Path = typer.Option(..., help="The client package directory"),
    file_encoding: str = typer.Option("utf-8", help="Encoding used when writing generated files"),
    base_class: str = typer.Option(DEFAULT_MODEL_BASE_CLASS, help="Base class for generated Pydantic models"),
    http_timeout: int = typer.Option(DEFAULT_HTTP_TIMEOUT, min=1, help="OpenAPI URL timeout in seconds"),
    fail_on_warning: bool = typer.Option(False, help="Return a non-zero status when model-import warnings occur"),
    require_api_required_arguments: bool | None = typer.Option(
        None,
        "--require-api-required-arguments/--no-require-api-required-arguments",
        help="Expose API-required inputs in signatures; overrides Python settings (default: disabled)",
    ),
) -> None:
    """Generate models and the async/sync SDK surfaces in one pass."""
    config = _process_config(
        url=url,
        path=path,
        smithy=smithy,
        overlays=overlay,
        service=service,
        package=package,
        client_name=client_name,
        vendor=vendor,
        python_settings_path=python_settings,
        output_path=output_path,
        file_encoding=file_encoding,
        base_class=base_class,
        http_timeout=http_timeout,
        require_api_required_arguments=require_api_required_arguments,
    )
    with _handle_codegen_errors():
        result = _render(config)
    written = write(result.modules, encoding=config.file_encoding)
    stale_generated = _orphaned_generated_modules(config.output_path, result.modules)
    for stale_path in stale_generated:
        stale_path.unlink()
    for module in result.modules:
        action = "preserved" if module.create_once and module.path not in written else "wrote"
        typer.echo(f"  {action}: {module.path}")
    for stale_path in stale_generated:
        typer.echo(f"  removed stale generated module: {stale_path}")
    typer.echo(f"generated {len(written)} files; preserved {len(result.modules) - len(written)} public extensions")
    handle_warnings(result.warnings, fail_on_warning)


@main.command()
def check(  # noqa: PLR0913, PLR0917 - Typer exposes each CLI option as a parameter
    url: str | None = typer.Option(None, help="A URL to read the OpenAPI document from"),
    path: Path | None = typer.Option(None, help="A path to the OpenAPI document"),
    smithy: list[Path] | None = typer.Option(None, "--smithy", help="Native Smithy source; may be repeated"),
    overlay: list[Path] | None = typer.Option(None, "--overlay", help="Smithy overlay file; may be repeated"),
    service: str | None = typer.Option(None, help="Smithy service shape ID; inferred when the model has one service"),
    package: str = typer.Option(..., help="Importable Python package name"),
    client_name: str = typer.Option(..., help="Generated aggregate client class name"),
    vendor: str | None = typer.Option(None, help="Readable vendor name used in generated documentation"),
    python_settings: Path | None = typer.Option(
        None,
        "--python-settings",
        help="JSON file containing Python generation policies, external models, adapters, and protocol preferences",
    ),
    output_path: Path = typer.Option(..., help="The client package directory"),
    file_encoding: str = typer.Option("utf-8", help="Encoding used by generated files"),
    base_class: str = typer.Option(DEFAULT_MODEL_BASE_CLASS, help="Base class for generated Pydantic models"),
    http_timeout: int = typer.Option(DEFAULT_HTTP_TIMEOUT, min=1, help="OpenAPI URL timeout in seconds"),
    fail_on_warning: bool = typer.Option(False, help="Return a non-zero status when model-import warnings occur"),
    require_api_required_arguments: bool | None = typer.Option(
        None,
        "--require-api-required-arguments/--no-require-api-required-arguments",
        help="Expose API-required inputs in signatures; overrides Python settings (default: disabled)",
    ),
) -> None:
    """Fail when committed generated output differs from clean generation."""
    config = _process_config(
        url=url,
        path=path,
        smithy=smithy,
        overlays=overlay,
        service=service,
        package=package,
        client_name=client_name,
        vendor=vendor,
        python_settings_path=python_settings,
        output_path=output_path,
        file_encoding=file_encoding,
        base_class=base_class,
        http_timeout=http_timeout,
        require_api_required_arguments=require_api_required_arguments,
    )
    with _handle_codegen_errors():
        result = _render(config)
    stale = [module.path for module in result.modules if not is_current(module, encoding=config.file_encoding)]
    stale.extend(_orphaned_generated_modules(config.output_path, result.modules))
    if stale:
        typer.echo("generated code is stale; run `spitzeisen-gen generate`:", err=True)
        for stale_path in stale:
            typer.echo(f"  {stale_path}", err=True)
        raise typer.Exit(code=1)
    typer.echo(f"{len(result.modules)} generated or scaffolded modules are up to date")
    handle_warnings(result.warnings, fail_on_warning)


def write(modules: list[GeneratedModule], *, encoding: str = "utf-8") -> set[Path]:
    """Atomically replace generated modules and preserve existing public scaffolds."""
    written: set[Path] = set()
    for module in modules:
        if module.create_once and module.path.exists():
            continue
        module.path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding=encoding,
            dir=module.path.parent,
            prefix=f".{module.path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary.write(module.source)
            temporary_path = Path(temporary.name)
        try:
            temporary_path.replace(module.path)
        finally:
            temporary_path.unlink(missing_ok=True)
        written.add(module.path)
    return written


def is_current(module: GeneratedModule, *, encoding: str = "utf-8") -> bool:
    """Whether generated output is current or a public scaffold already exists."""
    if not module.path.exists():
        return False
    return module.create_once or module.path.read_text(encoding=encoding) == module.source


def normalize_model_header(source: str) -> str:
    """Replace datamodel-code-generator's temporary filename with stable provenance."""
    match = MODEL_HEADER.match(source)
    if match is None:
        return source
    provenance = "the assembled Smithy model"
    return f"# Generated by datamodel-code-generator from {provenance}.\n{source[match.end() :]}"


def _render(config: Config) -> RenderResult:
    """Collect Java sources, run Pydantic, and validate the complete tree before writing."""
    inputs = load_compile_inputs(
        source=config.source,
        smithy_sources=config.smithy_sources,
        overlays=config.overlays,
        service=config.service,
        package=config.package,
        client_name=config.client_name,
        vendor=config.vendor,
        python_settings=_load_python_settings(config),
        timeout=config.http_timeout,
    )
    manifest = inputs.frontend.manifest
    _validate_handwritten_models(manifest, config.package, config.output_path)
    try:
        modules = [
            formatted_module(
                config.output_path / module.path,
                module.source,
                package=config.package,
                create_once=module.create_once,
            )
            for module in inputs.frontend.modules
        ]
        model_source = ""
        generated = [model for model in manifest.models if model.generated]
        if generated:
            model_source = generate_model_source(
                schema=inputs.model_schema,
                working_directory=_working_directory(config),
                manifest=manifest,
                package=config.package,
                package_root=config.output_path,
                base_class=config.base_class,
                encoding=config.file_encoding,
            )
            names = set(generated_model_names(model_source))
            missing = sorted(model.name for model in generated if model.name not in names)
            if missing:
                raise CodegenError(detail=f"the model backend did not generate response models {missing}")
            modules.append(GeneratedModule(config.output_path / "models" / "_generated.py", model_source))
        modules.append(model_exports_module(config.package, manifest.models, config.output_path, model_source))
    except subprocess.CalledProcessError as err:
        detail = (err.stderr or err.stdout or str(err)).strip()
        raise CodegenError(header="Model generation failed", detail=detail) from err
    except (ValueError, SyntaxError) as err:
        raise CodegenError(header="Python source generation failed", detail=str(err)) from err
    if manifest.dependencies:
        typer.echo("SDK requires these configured dependencies: " + ", ".join(manifest.dependencies))
    return RenderResult(modules=modules, warnings=inputs.warnings)


def _validate_handwritten_models(manifest: ArtifactManifest, package: str, package_root: Path) -> None:
    """Require configured local model modules without importing or executing user code."""
    missing: list[str] = []
    for model in manifest.models:
        if model.generated or not model.module.startswith(f"{package}."):
            continue
        path = package_root.joinpath(*model.module.removeprefix(f"{package}.").split("."))
        if not path.with_suffix(".py").is_file() and not (path / "__init__.py").is_file():
            missing.append(f"{model.module} ({model.name})")
    if missing:
        raise CodegenError(detail=f"configured external response models require existing local modules: {missing}")


def _load_python_settings(config: Config) -> dict[str, Any]:
    """Load target options; Java validates their contents once against the assembled model."""
    settings: dict[str, Any] = {}
    if config.python_settings_path is not None:
        try:
            document: object = json.loads(config.python_settings_path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as err:
            raise CodegenError(header="Invalid Python target settings", detail=str(err)) from err
        if not isinstance(document, dict):
            raise CodegenError(header="Invalid Python target settings", detail="expected a JSON object")
        settings = cast("dict[str, Any]", document)
    if config.require_api_required_arguments is not None:
        settings["require_api_required_arguments"] = config.require_api_required_arguments
    return settings


def generate_model_source(
    *,
    schema: dict[str, Any],
    working_directory: Path,
    manifest: ArtifactManifest,
    package: str,
    package_root: Path,
    base_class: str,
    encoding: str,
) -> str:
    """Run the replaceable Pydantic model backend and return reproducible source."""
    extra = ["--skip-root-model", "--collapse-root-models"]
    if aliases := manifest.model_aliases:
        extra += ["--aliases", json.dumps(aliases)]
    extra += ["--model-name-map", json.dumps(manifest.model_names)]
    with _temporary_sibling(working_directory / "jsonschema", suffix=".json") as model_input:
        model_input.write_text(json.dumps(schema, indent=2), encoding=encoding)
        with _temporary_sibling(package_root / "models" / "generated", suffix=".py") as output:
            subprocess.run(  # noqa: S603
                [
                    python_tool("datamodel-codegen"),
                    "--input",
                    str(model_input),
                    "--input-file-type",
                    "jsonschema",
                    "--output",
                    str(output),
                    "--output-model-type",
                    "pydantic_v2.BaseModel",
                    "--use-title-as-name",
                    "--disable-timestamp",
                    "--strict-nullable",
                    "--enum-field-as-literal",
                    "all",
                    "--base-class",
                    base_class,
                    "--reuse-model",
                    "--use-annotated",
                    "--field-constraints",
                    "--use-union-operator",
                    "--use-standard-collections",
                    "--use-schema-description",
                    "--use-field-description",
                    "--formatters",
                    "ruff-format",
                    *extra,
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            source = runtime_response_constraints(normalize_model_header(output.read_text(encoding=encoding)))
    destination = package_root / "models" / "_generated.py"
    return formatted_module(destination, source, package=package).source


def _working_directory(config: Config) -> Path:
    """Choose a writable directory near local inputs for temporary model-backend files."""
    if config.smithy_sources:
        return config.smithy_sources[0].parent
    if config.overlays:
        return config.overlays[0].parent
    if isinstance(config.source, Path):
        return config.source.parent
    return config.output_path.parent


@contextmanager
def _temporary_sibling(anchor: Path, *, suffix: str) -> Generator[Path]:
    """Yield a temporary path beside an input."""
    anchor.parent.mkdir(parents=True, exist_ok=True)
    descriptor, name = tempfile.mkstemp(dir=anchor.parent, prefix=".spitzeisen-", suffix=suffix)
    os.close(descriptor)
    path = Path(name)
    try:
        yield path
    finally:
        path.unlink(missing_ok=True)


def _orphaned_generated_modules(package_root: Path, modules: list[GeneratedModule]) -> list[Path]:
    """Find replaceable generated modules no longer present in the build plan."""
    expected = {module.path.resolve() for module in modules if not module.create_once}
    candidates: list[Path] = []
    for folder in (package_root / "_async" / "_generated", package_root / "_sync" / "_generated"):
        if folder.exists():
            candidates.extend(path for path in folder.glob("*.py") if path.name != "__init__.py")
    candidates.extend(
        path
        for path in (package_root / "models" / "_generated.py", package_root / "models" / "_exports.py")
        if path.exists()
    )
    return sorted(path for path in candidates if path.resolve() not in expected)


if __name__ == "__main__":
    main()
