"""The ``spitzeisen-gen`` command-line interface."""

from __future__ import annotations

import codecs
import json
import os
import re
import subprocess
import tempfile
from collections.abc import Generator, Sequence
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from pprint import pformat
from typing import Any

import typer
from pydantic import ValidationError

from spitzeisen.codegen import get_document, load_yaml_or_json
from spitzeisen.codegen.generate import (
    GeneratedModule,
    format_python,
    generate_plan,
    generated_model_names,
    model_exports_module,
    prune_spec,
)
from spitzeisen.codegen.manifest import Manifest
from spitzeisen.codegen.parser import GeneratorData
from spitzeisen.codegen.parser.errors import ErrorLevel, GeneratorError, ParseError
from spitzeisen.codegen.policy import ClientPlan, compile_manifest

DEFAULT_MODEL_BASE_CLASS = "spitzeisen.SpitzeisenModel"
DEFAULT_HTTP_TIMEOUT = 5
MODEL_HEADER = re.compile(
    r"\A# generated by datamodel-codegen:\r?\n#\s+filename:\s+(?P<filename>[^\r\n]+)\r?\n",
)


@dataclass(frozen=True, slots=True)
class Config:
    """Resolved command-line configuration."""

    source: str | Path
    config_path: Path
    output_path: Path
    file_encoding: str
    base_class: str
    http_timeout: int


@dataclass(frozen=True, slots=True)
class BuildInputs:
    """Hydrated source inputs and their compiled SDK plan."""

    manifest: Manifest
    spec: dict[str, Any]
    client: ClientPlan
    errors: tuple[GeneratorError, ...]


@dataclass(frozen=True, slots=True)
class RenderResult:
    """Rendered modules and non-fatal parser warnings."""

    modules: list[GeneratedModule]
    errors: tuple[GeneratorError, ...]


main = typer.Typer(name="spitzeisen-gen", no_args_is_help=True)


@main.callback()
def cli() -> None:
    """Generate a polished Python SDK from an OpenAPI document."""


def _process_config(
    *,
    url: str | None,
    path: Path | None,
    config_path: Path,
    output_path: Path,
    file_encoding: str,
    base_class: str,
    http_timeout: int,
) -> Config:
    """Resolve mutually exclusive sources using upstream's CLI rules."""
    source: str | Path
    if url and not path:
        source = url
    elif path and not url:
        source = path
    elif url and path:
        typer.secho("Provide either --url or --path, not both", fg=typer.colors.RED)
        raise typer.Exit(code=1)
    else:
        typer.secho("You must either provide --url or --path", fg=typer.colors.RED)
        raise typer.Exit(code=1)
    try:
        codecs.getencoder(file_encoding)
    except LookupError as err:
        typer.secho(f"Unknown encoding : {file_encoding}", fg=typer.colors.RED)
        raise typer.Exit(code=1) from err
    return Config(
        source=source,
        config_path=config_path,
        output_path=output_path,
        file_encoding=file_encoding,
        base_class=base_class,
        http_timeout=http_timeout,
    )


def _print_parser_error(err: GeneratorError, color: str) -> None:
    """Print one upstream-style generation error."""
    typer.secho(err.header, bold=True, fg=color, err=True)
    typer.echo(err=True)
    if err.detail:
        typer.secho(err.detail, fg=color, err=True)
        typer.echo(err=True)
    if isinstance(err, ParseError) and err.data is not None:
        typer.secho(pformat(err.data), fg=color, err=True)
    typer.echo(err=True)


def handle_errors(errors: Sequence[GeneratorError], fail_on_warning: bool = False) -> None:
    """Render parser/generator errors and choose the command exit status."""
    if not errors:
        return
    error_level = ErrorLevel.WARNING
    message = "Warning(s) encountered while generating. Client was generated, but some pieces may be missing"
    header_color = typer.colors.BRIGHT_YELLOW
    color = typer.colors.YELLOW
    for item in errors:
        if item.level is ErrorLevel.ERROR:
            error_level = ErrorLevel.ERROR
            message = "Error(s) encountered while generating, client was not created"
            header_color = typer.colors.BRIGHT_RED
            color = typer.colors.RED
            break
    typer.secho(message, underline=True, bold=True, fg=header_color, err=True)
    typer.echo(err=True)
    for item in errors:
        _print_parser_error(item, color)
    issue_link = typer.style(
        "https://github.com/feuerstein-org/spitzeisen/issues/new/choose",
        fg=typer.colors.BRIGHT_BLUE,
    )
    typer.secho(
        "If you believe this was a mistake or this tool is missing a feature you need, "
        f"please open an issue at {issue_link}",
        fg=typer.colors.BLUE,
        err=True,
    )
    if error_level is ErrorLevel.ERROR or fail_on_warning:
        raise typer.Exit(code=1)


def _command_config(
    *,
    url: str | None,
    path: Path | None,
    config_path: Path,
    output_path: Path,
    file_encoding: str,
    base_class: str,
    http_timeout: int,
) -> Config:
    """Share source/config processing between generation and drift checking."""
    return _process_config(
        url=url,
        path=path,
        config_path=config_path,
        output_path=output_path,
        file_encoding=file_encoding,
        base_class=base_class,
        http_timeout=http_timeout,
    )


@main.command()
def generate(
    url: str | None = typer.Option(None, help="A URL to read the OpenAPI document from"),
    path: Path | None = typer.Option(None, help="A path to the OpenAPI document"),
    config_path: Path = typer.Option(..., "--config", help="Path to the Spitzeisen manifest"),
    output_path: Path = typer.Option(..., help="The client package directory"),
    file_encoding: str = typer.Option("utf-8", help="Encoding used when writing generated files"),
    base_class: str = typer.Option(DEFAULT_MODEL_BASE_CLASS, help="Base class for generated Pydantic models"),
    http_timeout: int = typer.Option(DEFAULT_HTTP_TIMEOUT, min=1, help="OpenAPI URL timeout in seconds"),
    fail_on_warning: bool = typer.Option(False, help="Return a non-zero status when parser warnings occur"),
) -> None:
    """Generate models and the async/sync SDK surfaces in one pass."""
    config = _command_config(
        url=url,
        path=path,
        config_path=config_path,
        output_path=output_path,
        file_encoding=file_encoding,
        base_class=base_class,
        http_timeout=http_timeout,
    )
    result = _render(config)
    if isinstance(result, GeneratorError):
        handle_errors([result])
        return
    written = write(result.modules, encoding=config.file_encoding)
    stale_generated = _orphaned_generated_modules(config.output_path, result.modules)
    for stale_path in stale_generated:
        stale_path.unlink()
    for module in result.modules:
        action = "preserved" if module.create_once and module.path not in written else "wrote"
        typer.echo(f"  {action}: {module.path}")
    for stale_path in stale_generated:
        typer.echo(f"  removed stale generated module: {stale_path}")
    typer.echo(f"generated {len(written)} files; preserved {len(result.modules) - len(written)} public extensions")
    handle_errors(result.errors, fail_on_warning)


@main.command()
def check(
    url: str | None = typer.Option(None, help="A URL to read the OpenAPI document from"),
    path: Path | None = typer.Option(None, help="A path to the OpenAPI document"),
    config_path: Path = typer.Option(..., "--config", help="Path to the Spitzeisen manifest"),
    output_path: Path = typer.Option(..., help="The client package directory"),
    file_encoding: str = typer.Option("utf-8", help="Encoding used by generated files"),
    base_class: str = typer.Option(DEFAULT_MODEL_BASE_CLASS, help="Base class for generated Pydantic models"),
    http_timeout: int = typer.Option(DEFAULT_HTTP_TIMEOUT, min=1, help="OpenAPI URL timeout in seconds"),
    fail_on_warning: bool = typer.Option(False, help="Return a non-zero status when parser warnings occur"),
) -> None:
    """Fail when committed generated output differs from clean generation."""
    config = _command_config(
        url=url,
        path=path,
        config_path=config_path,
        output_path=output_path,
        file_encoding=file_encoding,
        base_class=base_class,
        http_timeout=http_timeout,
    )
    result = _render(config)
    if isinstance(result, GeneratorError):
        handle_errors([result])
        return
    stale = [module.path for module in result.modules if not is_current(module, encoding=config.file_encoding)]
    stale.extend(_orphaned_generated_modules(config.output_path, result.modules))
    if stale:
        typer.echo("generated code is stale; run `spitzeisen-gen generate`:", err=True)
        for stale_path in stale:
            typer.echo(f"  {stale_path}", err=True)
        raise typer.Exit(code=1)
    typer.echo(f"{len(result.modules)} generated or scaffolded modules are up to date")
    handle_errors(result.errors, fail_on_warning)


def load_manifest(path: Path) -> Manifest | GeneratorError:
    """Load the manifest with the same YAML/JSON parser used for OpenAPI."""
    try:
        loaded = load_yaml_or_json(path.read_bytes(), "application/json" if path.suffix == ".json" else None)
    except OSError as err:
        return GeneratorError(header="Unable to read config", detail=str(err))
    if isinstance(loaded, GeneratorError):
        loaded.header = "Unable to parse config"
        return loaded
    try:
        return Manifest.model_validate(loaded)
    except ValidationError as err:
        return GeneratorError(header="Unable to parse config", detail=str(err))


def write(modules: list[GeneratedModule], *, encoding: str = "utf-8") -> set[Path]:
    """Atomically replace generated modules and preserve existing public scaffolds."""
    written: set[Path] = set()
    for module in modules:
        if module.create_once and module.path.exists():
            continue
        module.path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding=encoding,
            dir=module.path.parent,
            prefix=f".{module.path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary.write(module.source)
            temporary_path = Path(temporary.name)
        try:
            temporary_path.replace(module.path)
        finally:
            temporary_path.unlink(missing_ok=True)
        written.add(module.path)
    return written


def is_current(module: GeneratedModule, *, encoding: str = "utf-8") -> bool:
    """Whether generated output is current or a public scaffold already exists."""
    if not module.path.exists():
        return False
    return module.create_once or module.path.read_text(encoding=encoding) == module.source


def normalize_model_header(source: str) -> str:
    """Replace datamodel-code-generator's temporary filename with stable provenance."""
    match = MODEL_HEADER.match(source)
    if match is None:
        return source
    return f"# Generated by datamodel-code-generator from selected OpenAPI operations.\n{source[match.end() :]}"


def _load_inputs(config: Config) -> BuildInputs | GeneratorError:
    """Load, hydrate, parse, and compile the two explicit inputs."""
    manifest = load_manifest(config.config_path)
    if isinstance(manifest, GeneratorError):
        return manifest
    try:
        spec = get_document(source=config.source, timeout=config.http_timeout)
    except OSError as err:
        return GeneratorError(header="Could not read OpenAPI document from provided path", detail=str(err))
    if isinstance(spec, GeneratorError):
        return spec
    openapi = GeneratorData.from_dict(spec)
    if isinstance(openapi, GeneratorError):
        return openapi
    try:
        client = compile_manifest(manifest, openapi)
    except ValueError as err:
        return GeneratorError(detail=str(err))
    errors: list[GeneratorError] = list(openapi.errors)
    for collection in openapi.endpoint_collections_by_tag.values():
        errors.extend(collection.parse_errors)
    return BuildInputs(manifest=manifest, spec=spec, client=client, errors=tuple(errors))


def _render(config: Config) -> RenderResult | GeneratorError:
    """Compile all inputs and render the complete output tree."""
    inputs = _load_inputs(config)
    if isinstance(inputs, GeneratorError):
        return inputs
    handwritten_error = _validate_handwritten_models(inputs.client, config.output_path)
    if handwritten_error is not None:
        return handwritten_error
    modules = generate_plan(inputs.client, config.output_path)
    generated_endpoints = tuple(endpoint for endpoint in inputs.client.endpoints if endpoint.generate_model)
    if generated_endpoints:
        try:
            model_source = _generate_model_source(
                spec=inputs.spec,
                working_directory=config.config_path.parent,
                manifest=inputs.manifest,
                client=inputs.client,
                package_root=config.output_path,
                base_class=config.base_class,
                encoding=config.file_encoding,
            )
        except subprocess.CalledProcessError as err:
            detail = (err.stderr or err.stdout or str(err)).strip()
            return GeneratorError(header="Model generation failed", detail=detail)
        generated_names = set(generated_model_names(model_source))
        missing_models = sorted(
            endpoint.model for endpoint in generated_endpoints if endpoint.model not in generated_names
        )
        if missing_models:
            return GeneratorError(
                detail=(
                    f"the model backend did not generate response models {missing_models}; "
                    "check response schema titles or set `generate_model: false`"
                ),
            )
        modules.append(GeneratedModule(config.output_path / "models" / "_generated.py", model_source))
        modules.append(model_exports_module(inputs.client, config.output_path, model_source))
    return RenderResult(modules=modules, errors=inputs.errors)


def _validate_handwritten_models(client: ClientPlan, package_root: Path) -> GeneratorError | None:
    """Require handwritten response-model modules for endpoints which opt out."""
    missing = [
        endpoint
        for endpoint in client.endpoints
        if not endpoint.generate_model and not (package_root / "models" / f"{endpoint.key}.py").exists()
    ]
    if not missing:
        return None
    paths = [f"models/{endpoint.key}.py ({endpoint.model})" for endpoint in missing]
    return GeneratorError(detail=f"generate_model=false requires handwritten model modules: {paths}")


def _generate_model_source(
    *,
    spec: dict[str, Any],
    working_directory: Path,
    manifest: Manifest,
    client: ClientPlan,
    package_root: Path,
    base_class: str,
    encoding: str,
) -> str:
    """Run the replaceable Pydantic model backend and return reproducible source."""
    extra: list[str] = []
    if aliases := manifest.model_aliases():
        extra += ["--aliases", json.dumps(aliases)]
    if overrides := manifest.model_type_overrides():
        extra += ["--type-overrides", json.dumps(overrides)]
    with _temporary_sibling(working_directory / "openapi", suffix=".json") as model_input:
        model_input.write_text(json.dumps(prune_spec(spec, client), indent=2), encoding=encoding)
        with _temporary_sibling(package_root / "models" / "generated", suffix=".py") as output:
            subprocess.run(  # noqa: S603
                [  # noqa: S607
                    "datamodel-codegen",
                    "--input",
                    str(model_input),
                    "--input-file-type",
                    "openapi",
                    "--openapi-scopes",
                    "paths",
                    "--output",
                    str(output),
                    "--output-model-type",
                    "pydantic_v2.BaseModel",
                    "--use-title-as-name",
                    "--disable-timestamp",
                    "--strict-nullable",
                    "--enum-field-as-literal",
                    "all",
                    "--base-class",
                    base_class,
                    "--reuse-model",
                    "--use-annotated",
                    "--field-constraints",
                    "--use-union-operator",
                    "--use-standard-collections",
                    "--use-schema-description",
                    "--use-field-description",
                    "--formatters",
                    "ruff-format",
                    *extra,
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            source = normalize_model_header(output.read_text(encoding=encoding))
    destination = package_root / "models" / "_generated.py"
    return format_python(source, str(destination))


@contextmanager
def _temporary_sibling(anchor: Path, *, suffix: str) -> Generator[Path]:
    """Yield a temporary path beside an input."""
    anchor.parent.mkdir(parents=True, exist_ok=True)
    descriptor, name = tempfile.mkstemp(dir=anchor.parent, prefix=".spitzeisen-", suffix=suffix)
    os.close(descriptor)
    path = Path(name)
    try:
        yield path
    finally:
        path.unlink(missing_ok=True)


def _orphaned_generated_modules(package_root: Path, modules: list[GeneratedModule]) -> list[Path]:
    """Find replaceable generated modules no longer present in the build plan."""
    expected = {module.path.resolve() for module in modules if not module.create_once}
    candidates: list[Path] = []
    for folder in (package_root / "_async" / "_generated", package_root / "_sync" / "_generated"):
        if folder.exists():
            candidates.extend(path for path in folder.glob("*.py") if path.name != "__init__.py")
    candidates.extend(
        path
        for path in (package_root / "models" / "_generated.py", package_root / "models" / "_exports.py")
        if path.exists()
    )
    return sorted(path for path in candidates if path.resolve() not in expected)


if __name__ == "__main__":
    main()
