"""
Generated synchronous WeatherApi client wiring.

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; add client-specific behaviour
to the public subclass beside the `_generated` package.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Self

from weather_sdk._sync.current_weather import SyncCurrentWeatherApi

if TYPE_CHECKING:
    from spitzeisen import SyncSpitzeisenConfig


class SyncWeatherApiBase:
    """Own and share one configuration across every generated operation API."""

    def __init__(self, config: SyncSpitzeisenConfig) -> None:
        """Build every operation API around the same connection-level configuration."""
        self.config = config

        self.current_weather_api = SyncCurrentWeatherApi(config)

        self._operation_apis = (self.current_weather_api,)

    def __enter__(self) -> Self:
        """Enter every operation API while sharing one lazily-created HTTP client."""
        for operation_api in self._operation_apis:
            operation_api.__enter__()
        return self

    def __exit__(self, *args: object) -> None:
        """Exit every operation API and close an owned HTTP client after the last holder."""
        for operation_api in reversed(self._operation_apis):
            operation_api.__exit__(*args)
