# Generated by spitzeisen-gen.
from __future__ import annotations

from typing import Self

from spitzeisen import SyncSpitzeisenConfig  # noqa: TC001 - retain runtime annotation introspection
from weather_sdk._sync.current_weather import SyncCurrentWeatherApi


class SyncWeatherApiBase:
    """Client for openweathermap. Shares one configuration across operation APIs."""

    def __init__(self, config: SyncSpitzeisenConfig) -> None:
        """Build all operation APIs around the supplied configuration."""
        self.config = config
        self.current_weather_api = SyncCurrentWeatherApi(config)
        self._operation_apis = (self.current_weather_api,)

    def __enter__(self) -> Self:
        """Enter each API while sharing one lazily-created HTTP client."""
        for operation_api in self._operation_apis:
            operation_api.__enter__()
        return self

    def __exit__(self, *args: object) -> None:
        """Release each API and close the shared owned client after its last holder."""
        for operation_api in reversed(self._operation_apis):
            operation_api.__exit__(*args)
