"""
Current Weather operation.

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit, run `mise run codegen`.
Vendor documentation: https://openweathermap.org/api/current?collection=current_forecast
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any, Literal

from spitzeisen import (
    NoPagination,
    ResponseShapeError,
    SpitzeisenOperationSpec,
    SyncSpitzeisenApi,
    build_header_params,
    coerce_choices,
    coerce_date,
    serialize_query_param,
)
from weather_sdk.models import Test
from weather_sdk.models.current_weather import CurrentWeatherResponse

CURRENT_WEATHER_OPERATION = SpitzeisenOperationSpec(
    path="/data/2.5/weather",
    cost=1.0,
    pagination=NoPagination(results_key=None),
)


class SyncCurrentWeatherApiBase(SyncSpitzeisenApi):
    """
    Generated request layer for the current weather operation.

    Subclassed by `SyncCurrentWeatherApi`, which is where any hand-written behaviour
    belongs - this class is regenerated and never edited.
    """

    def get_current_weather_raw(
        self,
        *,
        latitude: str | date | datetime,
        longitude: list[str],
        unittt: Literal["standard", "metric", "imperial"] = "test",
        language: list[Test] | None = None,
    ) -> dict[str, Any] | None:
        """
        Fetch the raw JSON object, without validation.

        Returns None when the resource does not exist (HTTP 404), which this operation treats
        as a routine outcome rather than a failure.
        """
        params = [
            *serialize_query_param(
                coerce_date(latitude, "latitude"),
                name="lat",
                style="form",
                explode=False,
                required=True,
                param_name="latitude",
            ),
            *serialize_query_param(
                ",".join(longitude) if longitude else None,
                name="lon",
                style="form",
                explode=False,
                required=True,
                param_name="longitude",
            ),
            *serialize_query_param(
                unittt,
                name="units",
                style="form",
                explode=False,
                required=False,
                param_name="unittt",
            ),
            *serialize_query_param(
                coerce_choices(language, Test, "language"),
                name="lang",
                style="form",
                explode=False,
                required=False,
                param_name="language",
            ),
        ]
        headers = build_header_params(
            {},
        )
        data = self._request_optional(
            CURRENT_WEATHER_OPERATION,
            params=params,
            headers=headers,
        )
        if data is None:
            return None
        if not isinstance(data, dict):
            msg = "expected the current weather response body to be an object"
            raise ResponseShapeError(msg)
        # No envelope: the body is the object.
        return data

    def get_current_weather(
        self,
        *,
        latitude: str | date | datetime,
        longitude: list[str],
        unittt: Literal["standard", "metric", "imperial"] = "test",
        language: list[Test] | None = None,
    ) -> CurrentWeatherResponse | None:
        """
        Fetch the current weather observation for one location.

        Fetches the response, then validates it.

        Docs: https://openweathermap.org/api/current?collection=current_forecast

        Example::

            with SyncWeatherApi(config) as api:
                result = api.current_weather_api.get_current_weather(latitude=..., longitude=...)

        Args:
            latitude: Latitude of the location.
            longitude: Longitude of the location.
            unittt: Units of measurement. Standard units are used by default.
            language: Language code used for the city name and weather description.

        Returns:
            A validated `CurrentWeatherResponse`, or None when the resource does not exist (HTTP 404).

        Raises:
            pydantic.ValidationError: If the response payload does not match.


        """
        raw = self.get_current_weather_raw(
            latitude=latitude,
            longitude=longitude,
            unittt=unittt,
            language=language,
        )
        if raw is None:
            return None
        return CurrentWeatherResponse.model_validate(raw)
