# Generated by spitzeisen-gen.
from __future__ import annotations

from typing import Any, Literal

from spitzeisen import (
    NoPagination,
    ResponseShapeError,
    SpitzeisenOperationSpec,
    SyncSpitzeisenApi,
    build_header_params,
    coerce_choice,
    serialize_query_param,
)
from spitzeisen.params import QueryParams  # noqa: TC001 - retain runtime annotation introspection
from weather_sdk.models.current_weather_response import CurrentWeatherResponse

_OPERATION = SpitzeisenOperationSpec(path="/data/2.5/weather", cost=1, pagination=NoPagination(results_key=None))


class SyncCurrentWeatherApiBase(SyncSpitzeisenApi):
    """Generated request layer. Customize the public SyncCurrentWeatherApi subclass."""

    def get_current_weather_raw(
        self,
        *,
        latitude: float,
        longitude: float,
        units: Literal["standard", "metric", "imperial"] = "standard",
        language: str | None = None,
    ) -> dict[str, Any] | None:
        """Fetch raw JSON without model validation. See get_current_weather for parameter documentation."""
        latitude = self._validate_input(latitude, float)
        longitude = self._validate_input(longitude, float)
        units = self._validate_input(units, Literal["standard", "metric", "imperial"])
        language = self._validate_input(language, str | None)
        params: QueryParams = [
            *serialize_query_param(
                latitude, name="lat", style="form", explode=True, required=True, param_name="latitude"
            ),
            *serialize_query_param(
                longitude, name="lon", style="form", explode=True, required=True, param_name="longitude"
            ),
            *serialize_query_param(
                coerce_choice(units, Literal["standard", "metric", "imperial"], "units"),
                name="units",
                style="form",
                explode=True,
                required=False,
                param_name="units",
            ),
            *serialize_query_param(
                language, name="lang", style="form", explode=True, required=False, param_name="language"
            ),
        ]
        headers = build_header_params({})
        data = self._request_optional(
            _OPERATION,
            params=params,
            headers=headers,
        )
        if data is None:
            return None
        if not isinstance(data, dict):
            message = "expected a response object"
            raise ResponseShapeError(message)
        return data

    def get_current_weather(
        self,
        *,
        latitude: float,
        longitude: float,
        units: Literal["standard", "metric", "imperial"] = "standard",
        language: str | None = None,
    ) -> CurrentWeatherResponse | None:
        """
        Returns the current weather observation for one latitude and longitude.

        Fetch and validate the response.

        Example::

            with SyncWeatherApi(config) as api:
                result = api.current_weather_api.get_current_weather(latitude=..., longitude=...)

        Args:
            latitude: Latitude of the location.
            longitude: Longitude of the location.
            units: Units of measurement. Standard units are used by default.
            language: Language code used for the city name and weather description.

        Returns:
            Validated response, or None for HTTP 404.

        Raises:
            pydantic.ValidationError: Invalid response data.
            ValueError: Invalid input.

        """
        raw = self.get_current_weather_raw(
            latitude=latitude,
            longitude=longitude,
            units=units,
            language=language,
        )
        if raw is None:
            return None
        return CurrentWeatherResponse.model_validate(raw)
